In [ ]:
!pip install numpy --upgrade
!pip install opencv-python
!pip install ghostscript
!pip install camelot-py
!pip install pdfplumber

In [2]:
import camelot
tables = camelot.read_pdf('https://or.ump.edu.my/or/CourseCatalog/COURSE_CATALOG_IJA.pdf', pages='345-384')

for i in range(len(tables)):
    tables[i].df = tables[i].df.replace('\\n',' ', regex=True)
    display(tables[i].df)

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01G,FRI,10:00-10:50 11:00-11:50,FSK15 FSK15,,36 36,Y 30/01/2024 - AM,01469 - LSC
3,,THU,08:00-08:50 09:00-09:50,Z01-0004 Z01-0004,B B L L B B L L,36 36,,
4,02G,FRI,08:00-08:50 09:00-09:50,FSK15 FSK15,,36 36,Y 30/01/2024 - AM,01469 - LSC
5,,THU,08:00-08:50 09:00-09:50,Z01-0004 Z01-0004,,36 36,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
2,01G,FRI,08:00-08:50 09:00-09:50,FSK14 FSK14,,36 36,Y 25/01/2024 - AM,TBA0001 - ES(
3,,TUE,08:00-08:50 09:00-09:50,Z01-0004 Z01-0004,B B L L B B L L,36 36,,
4,02G,FRI,10:00-10:50 11:00-11:50,FSK14 FSK14,,35 35,Y 25/01/2024 - AM,TBA0001 - ES(
5,,TUE,08:00-08:50 09:00-09:50,Z01-0004 Z01-0004,,35 35,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01A,WED,12:00-12:50 13:00-13:50,FKPPT- L- 01B FKPPT- L- 01B,,30 30,N,01100 - ZRBMA
3,01B,WED,12:00-12:50 13:00-13:50,FKPPT- L- 01B FKPPT- L- 01B,,30 30,N,01100 - ZRBMA
4,01G,MON,12:00-12:50 13:00-13:50,W-DK-13 W-DK-13,,60 60,N,01100 - ZRBMA
5,02A,THU,12:00-12:50 13:00-13:50,FKPPT- L- 01B FKPPT- L- 01B,,30 30,N,01100 - ZRBMA
6,02B,THU,12:00-12:50 13:00-13:50,FKPPT- L- 01B FKPPT- L- 01B,,30 30,N,01100 - ZRBMA
7,02G,TUE,12:00-12:50 13:00-13:50,W-DK-13 W-DK-13,,60 60,N,01100 - ZRBMA
8,03A,WED,14:00-14:50 15:00-15:50,ET-L-01 ET-L-01,,20 20,N,01985 - M'BM
9,03B,WED,14:00-14:50 15:00-15:50,ET-L-01 ET-L-01,,20 20,N,01985 - M'BM
10,03G,FRI,10:00-10:50 11:00-11:50,Y-DK-03 Y-DK-03,B B B B L L B B B B L L B B B B L L B B B B L ...,40 40,N,01985 - M'BM
11,04A,FRI,10:00-10:50 11:00-11:50,ET-L-02 ET-L-02,,30 30,N,FP0040 - IBMA
12,04B,THU,08:00-08:50 09:00-09:50,ET-L-02 ET-L-02,,30 30,N,FP0040 - IBMA
13,04G,WED,08:00-08:50 09:00-09:50,Y01-0018 Y01-0018,,60 60,N,FP0040 - IBMA
14,06A,WED,10:00-10:50 11:00-11:50,FSK12 FSK12,,30 30,N,FP0040 - IBMA
15,06B,WED,10:00-10:50 11:00-11:50,FSK12 FSK12,,30 30,N,FP0040 - IBMA
16,06G,MON,10:00-10:50 11:00-11:50,Y01-1010 Y01-1010,,60 60,N,FP0040 - IBMA
17,07A,TUE,14:00-14:50 15:00-15:50,ETIM-L-01 ETIM-L-01,,30 30,N,01985 - M'BM
18,07G,WED,08:00-08:50 09:00-09:50,ETIM-L-01 ETIM-L-01,,30 30,N,01985 - M'BM
19,Semester II Academic Session 2023/2024,,,,,,,
20,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
21,01A,WED,12:00-12:50 13:00-13:50,FKPPT- L- 01B FKPPT- L- 01B,,30 30,N,FP0040 - IBMA
22,01B,WED,12:00-12:50 13:00-13:50,FKPPT- L- 01B FKPPT- L- 01B,,30 30,N,FP0040 - IBMA
23,01G,MON,12:00-12:50 13:00-13:50,W-DK-13 W-DK-13,,60 60,N,FP0040 - IBMA
24,02A,THU,12:00-12:50 13:00-13:50,FKPPT- L- 01B FKPPT- L- 01B,,30 30,N,FP0040 - IBMA
25,02B,THU,12:00-12:50 13:00-13:50,FKPPT- L- 01B FKPPT- L- 01B,,30 30,N,FP0040 - IBMA
26,02G,TUE,12:00-12:50 13:00-13:50,W-DK-13 W-DK-13,,60 60,N,FP0040 - IBMA
27,04A,THU,14:00-14:50 15:00-15:50,ET-L-01 ET-L-01,,30 30,N,01100 - ZRBMA
28,04G,TUE,14:00-14:50 15:00-15:50,ET-L-01 ET-L-01,,30 30,N,01100 - ZRBMA
29,05A,THU,16:00-16:50 17:00-17:50,FTA16L FTA16L,B B B B L L B B B B L L B B L L B B B B L L B ...,30 30,N,01469 - LSC
30,05B,THU,16:00-16:50 17:00-17:50,FTA16L FTA16L,,30 30,N,01469 - LSC
31,05G,TUE,16:00-16:50 17:00-17:50,W-DKU-K-01 W-DKU-K-01,,60 60,N,01469 - LSC
32,06A,THU,08:00-08:50 09:00-09:50,ET-L-02 ET-L-02,,30 30,N,01469 - LSC
33,06B,THU,08:00-08:50 09:00-09:50,ET-L-02 ET-L-02,,30 30,N,01469 - LSC
34,06G,MON,10:00-10:50 11:00-11:50,Y01-1010 Y01-1010,,60 60,N,01469 - LSC
35,07A,WED,14:00-14:50 15:00-15:50,FKASA11B FKASA11B,,30 30,N,0544 - JBS
36,07G,MON,14:00-14:50 15:00-15:50,FKASA11A FKASA11A,,30 30,N,0544 - JBS
37,08A,THU,12:00-12:50 13:00-13:50,FKASA11A FKASA11A,,30 30,N,0544 - JBS

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
2,01G,MON,10:00-10:50 11:00-11:50,Z01-0003 Z01-0003,,35 35,Y 25/01/2024 - AM,01918 - YBMN
3,,TUE,08:00-08:50 09:00-09:50,FSK14 FSK14,L L B B L L B B,35 35,,
4,02G,MON,10:00-10:50 11:00-11:50,Z01-0003 Z01-0003,,30 30,Y 25/01/2024 - AM,01918 - YBMN
5,,TUE,12:00-12:50 13:00-13:50,FSK14 FSK14,,30 30,,

,0,1,2,3,4,5,6,7
0,Semester II Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01G,THU,10:00-10:50 11:00-11:50,FSK14 FSK14,,35 35,Y 27/06/2024 - AM,01918 - YBMN
3,,WED,10:00-10:50 11:00-11:50,Z01-0003 Z01-0003,B B L L B B L L,35 35,,
4,02G,THU,14:00-14:50 15:00-15:50,FSK14 FSK14,,35 35,Y 27/06/2024 - AM,01918 - YBMN
5,,WED,10:00-10:50 11:00-11:50,Z01-0003 Z01-0003,,35 35,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap Exam Staff,,,,,,,
2,L L B B 01 WED 10:00-10:50 BZ-02-100 30 Y 0165...,,,,,,,
3,01A MON 10:00-10:50 BZ-03-083 30 Y 01657 - ZBM...,,,,,,,
4,Semester II Academic Session 2023/2024,,,,,,,
5,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
6,01,MON,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 27/06/2024 - AM,01746 - MABI
7,01A,FRI,10:00-10:50 11:00-11:50,BZ-03-083 BZ-03-083,,30 30,Y 27/06/2024 - AM,01746 - MABI
8,01B,FRI,08:00-08:50 09:00-09:50,BZ-03-083 BZ-03-083,,30 30,Y 27/06/2024 - AM,01746 - MABI
9,02,TUE,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 27/06/2024 - AM,01746 - MABI
10,02A,MON,16:00-16:50 17:00-17:50,BZ-03-083 BZ-03-083,,30 30,Y 27/06/2024 - AM,01746 - MABI
11,02B,MON,14:00-14:50 15:00-15:50,BZ-03-083 BZ-03-083,L L B B B B L L B B B B L L B B B B L L B B B B,30 30,Y 27/06/2024 - AM,01746 - MABI
12,03,FRI,10:00-10:50 11:00-11:50,BZ-01-121 BZ-01-121,,60 60,Y 27/06/2024 - AM,01469 - LSC
13,03A,MON,10:00-10:50 11:00-11:50,BZ-03-083 BZ-03-083,,30 30,Y 27/06/2024 - AM,01469 - LSC
14,03B,TUE,12:00-12:50 13:00-13:50,BZ-03-083 BZ-03-083,,30 30,Y 27/06/2024 - AM,01469 - LSC
15,04,MON,16:00-16:50 17:00-17:50,BZ-02-100 BZ-02-100,,60 60,Y 27/06/2024 - AM,01469 - LSC
16,04A,TUE,10:00-10:50 11:00-11:50,BZ-03-083 BZ-03-083,,30 30,Y 27/06/2024 - AM,01469 - LSC
17,04B,THU,12:00-12:50 13:00-13:50,BZ-03-083 BZ-03-083,,30 30,Y 27/06/2024 - AM,01469 - LSC

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,08:00-08:50 09:00-09:50,BZ-02-096 BZ-02-096,,62 62,Y 25/01/2024 - AM,S1287 - NAFBZ
3,01A,WED,08:00-08:50 09:00-09:50,BZ-03-083 BZ-03-083,,31 31,Y 25/01/2024 - AM,S1287 - NAFBZ
4,01B,WED,10:00-10:50 11:00-11:50,BZ-03-083 BZ-03-083,,31 31,Y 25/01/2024 - AM,S1287 - NAFBZ
5,02,TUE,10:00-10:50 11:00-11:50,BZ-02-105 BZ-02-105,,62 62,Y 25/01/2024 - AM,01866 - SBM@A
6,02A,THU,08:00-08:50 09:00-09:50,BZ-03-083 BZ-03-083,,31 31,Y 25/01/2024 - AM,01866 - SBM@A
7,02B,THU,10:00-10:50 11:00-11:50,BZ-03-083 BZ-03-083,L L B B B B L L B B B B L L B B B B L L B B B B,31 31,Y 25/01/2024 - AM,01866 - SBM@A
8,03,TUE,14:00-14:50 15:00-15:50,BZ-02-105 BZ-02-105,,62 62,Y 25/01/2024 - AM,01866 - SBM@A
9,03A,THU,14:00-14:50 15:00-15:50,BZ-03-083 BZ-03-083,,31 31,Y 25/01/2024 - AM,01866 - SBM@A
10,03B,THU,16:00-16:50 17:00-17:50,BZ-03-083 BZ-03-083,,31 31,Y 25/01/2024 - AM,01866 - SBM@A
11,04,THU,08:00-08:50 09:00-09:50,BZ-01-121 BZ-01-121,,62 62,Y 25/01/2024 - AM,01657 - ZBM
12,04A,TUE,08:00-08:50 09:00-09:50,BZ-03-083 BZ-03-083,,31 31,Y 25/01/2024 - AM,01657 - ZBM
13,04B,TUE,10:00-10:50 11:00-11:50,BZ-03-083 BZ-03-083,,31 31,Y 25/01/2024 - AM,01657 - ZBM
14,Semester II Academic Session 2023/2024,,,,,,,
15,Sec Day Time Loc Mode Cap Exam Staff,,,,,,,
16,L L B B 01 MON 10:00-10:50 BZ-01-124 30 Y 27/0...,,,,,,,
17,01A FRI 10:00-10:50 BZ-01-100 30 Y 27/06/2024 ...,,,,,,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
2,01,WED,08:00-08:50 09:00-09:50,BZ-01-124 BZ-01-124,,60 60,N,01178 - SNBI
3,01A,MON,10:00-10:50 11:00-11:50,BZ-02-050 BZ-02-050,L L B B B B,30 30,N,01178 - SNBI
4,01B,THU,12:00-12:50 13:00-13:50,BZ-02-050 BZ-02-050,,30 30,N,01178 - SNBI

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,TUE,10:00-10:50 11:00-11:50,BZ-02-104 BZ-02-104,,90 90,Y 26/01/2024 - AM,01993 - ABAR
3,01A,THU,08:00-08:50 09:00-09:50,BZ-02-062 BZ-02-062,,30 30,Y 26/01/2024 - AM,01993 - ABAR
4,01B,THU,10:00-10:50 11:00-11:50,BZ-02-062 BZ-02-062,,30 30,Y 26/01/2024 - AM,01993 - ABAR
5,01C,FRI,10:00-10:50 11:00-11:50,BZ-02-062 BZ-02-062,,30 30,Y 26/01/2024 - AM,01993 - ABAR
6,02,TUE,14:00-14:50 15:00-15:50,BZ-02-106 BZ-02-106,L L B B B B B B L L B B B B L L B B B B,60 60,Y 26/01/2024 - AM,01852 - NSNBI
7,02A,THU,14:00-14:50 15:00-15:50,BZ-02-062 BZ-02-062,,30 30,Y 26/01/2024 - AM,01852 - NSNBI
8,02B,THU,16:00-16:50 17:00-17:50,BZ-02-062 BZ-02-062,,30 30,Y 26/01/2024 - AM,01852 - NSNBI
9,03,WED,12:00-12:50 13:00-13:50,BZ-02-106 BZ-02-106,,60 60,Y 26/01/2024 - AM,01852 - NSNBI
10,03A,MON,12:00-12:50 13:00-13:50,BZ-02-062 BZ-02-062,,30 30,Y 26/01/2024 - AM,01852 - NSNBI
11,03B,MON,14:00-14:50 15:00-15:50,BZ-02-062 BZ-02-062,,30 30,Y 26/01/2024 - AM,01852 - NSNBI

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
2,01,MON,12:00-12:50 13:00-13:50,BZ-02-065 BZ-02-065,,33 33,N,01194 - ZBD
3,01A,WED,12:00-12:50 13:00-13:50,BZ-02-065 BZ-02-065,,33 33,N,01194 - ZBD
4,02,TUE,12:00-12:50 13:00-13:50,BZ-02-065 BZ-02-065,L L B B L L B B L L B B,33 33,N,01194 - ZBD
5,02A,THU,12:00-12:50 13:00-13:50,BZ-02-065 BZ-02-065,,33 33,N,01194 - ZBD
6,03,TUE,08:00-08:50 09:00-09:50,BZ-02-065 BZ-02-065,,33 33,N,01194 - ZBD
7,03A,THU,08:00-08:50 09:00-09:50,BZ-02-065 BZ-02-065,,33 33,N,01194 - ZBD

,0,1,2,3,4,5,6,7
0,Semester II Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,08:00-08:50 09:00-09:50,BZ-01-121 BZ-01-121,,30 30,Y 02/07/2024 - AM,01982 - ZBI
3,01B,TUE,16:00-16:50 17:00-17:50,BZ-04-063 BZ-04-063,,30 30,Y 02/07/2024 - AM,01982 - ZBI
4,02,THU,08:00-08:50 09:00-09:50,BZ-01-121 BZ-01-121,,60 60,Y 02/07/2024 - AM,TBA0001 - ES(
5,02A,THU,14:00-14:50 15:00-15:50,BZ-04-063 BZ-04-063,,30 30,Y 02/07/2024 - AM,TBA0001 - ES(
6,02B,THU,16:00-16:50 17:00-17:50,BZ-04-063 BZ-04-063,L L B B L L B B B B L L B B B B L L B B,30 30,Y 02/07/2024 - AM,TBA0001 - ES(
7,03,MON,14:00-14:50 15:00-15:50,BZ-02-106 BZ-02-106,,60 60,Y 02/07/2024 - AM,01982 - ZBI
8,03A,TUE,08:00-08:50 09:00-09:50,BZ-04-063 BZ-04-063,,30 30,Y 02/07/2024 - AM,TBA0001 - ES(
9,03B,TUE,10:00-10:50 11:00-11:50,BZ-04-063 BZ-04-063,,30 30,Y 02/07/2024 - AM,TBA0001 - ES(
10,04,WED,08:00-08:50 09:00-09:50,BZ-01-121 BZ-01-121,,30 30,Y 02/07/2024 - AM,01982 - ZBI
11,04A,TUE,14:00-14:50 15:00-15:50,BZ-04-063 BZ-04-063,,30 30,Y 02/07/2024 - AM,01982 - ZBI

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,THU,10:00-10:50 11:00-11:50,BZ-02-105 BZ-02-105,,120 120,Y 29/01/2024 - AM,0549 - FBZ
3,01A,MON,10:00-10:50 11:00-11:50,BZ-01-092 BZ-01-092,,30 30,Y 29/01/2024 - AM,0549 - FBZ
4,01B,MON,08:00-08:50 09:00-09:50,BZ-01-092 BZ-01-092,L L T T T T T T T T,30 30,Y 29/01/2024 - AM,0549 - FBZ
5,01C,WED,08:00-08:50 09:00-09:50,BZ-01-092 BZ-01-092,,30 30,Y 29/01/2024 - AM,0549 - FBZ
6,01D,TUE,08:00-08:50 09:00-09:50,BZ-01-092 BZ-01-092,,30 30,Y 29/01/2024 - AM,0549 - FBZ
7,Semester II Academic Session 2023/2024,,,,,,,
8,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
9,01,WED,10:00-10:50 11:00-11:50,BZ-02-105 BZ-02-105,,90 90,Y 03/07/2024 - AM,0549 - FBZ
10,01A,TUE,16:00-16:50 17:00-17:50,BZ-01-092 BZ-01-092,L L T T T T T T,30 30,Y 03/07/2024 - AM,0549 - FBZ
11,01B,TUE,14:00-14:50 15:00-15:50,BZ-01-092 BZ-01-092,,30 30,Y 03/07/2024 - AM,0549 - FBZ
12,01C,THU,14:00-14:50 15:00-15:50,BZ-01-092 BZ-01-092,,30 30,Y 03/07/2024 - AM,0549 - FBZ

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,14:00-14:50 15:00-15:50,BZ-01-124 BZ-01-124,,50 50,Y 30/01/2024 - PM,01980 - NHBI
3,01A,TUE,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,,20 20,Y 30/01/2024 - PM,01980 - NHBI
4,01B,TUE,10:00-10:50 11:00-11:50,BZ-03-076 BZ-03-076,L L B B B B L L B B B B,30 30,Y 30/01/2024 - PM,01980 - NHBI
5,02,THU,14:00-14:50 15:00-15:50,BZ-01-124 BZ-01-124,,40 40,Y 30/01/2024 - PM,0044 - RBAB
6,02A,THU,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,,14 14,Y 30/01/2024 - PM,01980 - NHBI
7,02B,THU,10:00-10:50 11:00-11:50,BZ-02-090 BZ-02-090,,26 26,Y 30/01/2024 - PM,01980 - NHBI
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
10,01,THU,10:00-10:50 11:00-11:50,BZ-02-100 BZ-02-100,,60 60,Y 26/06/2024 - PM,0043 - MBAM
11,01A,THU,14:00-14:50 15:00-15:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - PM,0043 - MBAM
12,01B,THU,16:00-16:50 17:00-17:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - PM,0043 - MBAM
13,02,FRI,08:00-08:50 09:00-09:50,BZ-02-100 BZ-02-100,,60 60,Y 26/06/2024 - PM,01443 - MIBUO
14,02A,MON,08:00-08:50 09:00-09:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - PM,01443 - MIBUO
15,02B,MON,10:00-10:50 11:00-11:50,BZ-03-076 BZ-03-076,L L B B B B L L B B B B L L B B B B L L B B B B,30 30,Y 26/06/2024 - PM,01443 - MIBUO
16,03,MON,14:00-14:50 15:00-15:50,BZ-02-100 BZ-02-100,,60 60,Y 26/06/2024 - PM,0043 - MBAM
17,03A,TUE,08:00-08:50 09:00-09:50,BZ-04-068 BZ-04-068,,30 30,Y 26/06/2024 - PM,TBA0001 - ES(
18,03B,TUE,10:00-10:50 11:00-11:50,BZ-04-068 BZ-04-068,,30 30,Y 26/06/2024 - PM,TBA0001 - ES(
19,04,TUE,14:00-14:50 15:00-15:50,BZ-02-100 BZ-02-100,,60 60,Y 26/06/2024 - PM,01980 - NHBI
20,04A,WED,08:00-08:50 09:00-09:50,BZ-04-068 BZ-04-068,,30 30,Y 26/06/2024 - PM,01980 - NHBI
21,04B,WED,10:00-10:50 11:00-11:50,BZ-04-068 BZ-04-068,,30 30,Y 26/06/2024 - PM,0043 - MBAM

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,16:00-16:50 17:00-17:50,BZ-01-121 BZ-01-121,,60 60,Y 30/01/2024 - AM,01805 - NABS
3,01A,TUE,10:00-10:50 11:00-11:50,BZ-03-089 BZ-03-089,,30 30,Y 30/01/2024 - AM,01805 - NABS
4,01B,THU,12:00-12:50 13:00-13:50,BZ-03-089 BZ-03-089,L L B B B B L L B B,30 30,Y 30/01/2024 - AM,01805 - NABS
5,02,MON,16:00-16:50 17:00-17:50,BZ-01-121 BZ-01-121,,30 30,Y 30/01/2024 - AM,01805 - NABS
6,02A,THU,10:00-10:50 11:00-11:50,BZ-03-089 BZ-03-089,,30 30,Y 30/01/2024 - AM,01805 - NABS
7,Semester II Academic Session 2023/2024,,,,,,,
8,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
9,01,MON,16:00-16:50 17:00-17:50,BZ-01-124 BZ-01-124,,60 60,Y 01/07/2024 - AM,0120 - NBA
10,01A,TUE,10:00-10:50 11:00-11:50,BZ-03-089 BZ-03-089,,30 30,Y 01/07/2024 - AM,0120 - NBA
11,01B,THU,12:00-12:50 13:00-13:50,BZ-03-089 BZ-03-089,,30 30,Y 01/07/2024 - AM,0120 - NBA
12,02,THU,16:00-16:50 17:00-17:50,BZ-01-124 BZ-01-124,,60 60,Y 01/07/2024 - AM,01805 - NABS
13,02A,THU,10:00-10:50 11:00-11:50,BZ-03-089 BZ-03-089,L L B B B B L L B B B B L L B B B B,30 30,Y 01/07/2024 - AM,01805 - NABS
14,02B,MON,12:00-12:50 13:00-13:50,BZ-03-089 BZ-03-089,,30 30,Y 01/07/2024 - AM,01805 - NABS
15,03,WED,08:00-08:50 09:00-09:50,BZ-01-124 BZ-01-124,,60 60,Y 01/07/2024 - AM,0120 - NBA
16,03A,TUE,14:00-14:50 15:00-15:50,BZ-03-089 BZ-03-089,,30 30,Y 01/07/2024 - AM,0120 - NBA
17,03B,TUE,16:00-16:50 17:00-17:50,BZ-03-089 BZ-03-089,,21 21,Y 01/07/2024 - AM,0120 - NBA

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,FRI,10:00-10:50 11:00-11:50,BZ-02-105 BZ-02-105,,75 75,Y 29/01/2024 - PM,01444 - ASBL
3,01A,MON,10:00-10:50 11:00-11:50,BZ-02-049 BZ-02-049,L L B B B B B B,30 30,Y 29/01/2024 - PM,0374 - SBA
4,01B,TUE,12:00-12:50 13:00-13:50,BZ-02-049 BZ-02-049,,30 30,Y 29/01/2024 - PM,0374 - SBA
5,01C,WED,10:00-10:50 11:00-11:50,BZ-02-049 BZ-02-049,,15 15,Y 29/01/2024 - PM,0881 - BBY
6,Semester II Academic Session 2023/2024,,,,,,,
7,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
8,01,FRI,10:00-10:50 11:00-11:50,BZ-02-105 BZ-02-105,,75 75,Y 28/06/2024 - PM,0374 - SBA
9,01A,MON,10:00-10:50 11:00-11:50,BZ-01-066 BZ-01-066,L L B B B B B B,25 25,Y 28/06/2024 - PM,0374 - SBA
10,01B,TUE,12:00-12:50 13:00-13:50,BZ-01-066 BZ-01-066,,25 25,Y 28/06/2024 - PM,0374 - SBA
11,01C,WED,12:00-12:50 13:00-13:50,BZ-01-066 BZ-01-066,,25 25,Y 28/06/2024 - PM,0374 - SBA

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap Exam Staff,,,,,,,
2,L L B B 01 MON 10:00-10:50 BZ-02-106 30 Y 30/0...,,,,,,,
3,01A WED 10:00-10:50 BZ-02-059 30 Y 30/01/2024 ...,,,,,,,
4,Semester II Academic Session 2023/2024,,,,,,,
5,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
6,01,WED,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 28/06/2024 - AM,01679 - SFBK
7,01A,TUE,16:00-16:50 17:00-17:50,BZ-02-059 BZ-02-059,,30 30,Y 28/06/2024 - AM,01679 - SFBK
8,01B,TUE,14:00-14:50 15:00-15:50,BZ-02-059 BZ-02-059,L L B B B B L L B B B B,30 30,Y 28/06/2024 - AM,01679 - SFBK
9,02,MON,14:00-14:50 15:00-15:50,BZ-02-096 BZ-02-096,,60 60,Y 28/06/2024 - AM,01990 - HWS
10,02A,TUE,08:00-08:50 09:00-09:50,BZ-02-059 BZ-02-059,,30 30,Y 28/06/2024 - AM,0882 - RNBR
11,02B,TUE,10:00-10:50 11:00-11:50,BZ-02-059 BZ-02-059,,30 30,Y 28/06/2024 - AM,0882 - RNBR

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,12:00-12:50,BZ-02-106,,30,Y 31/01/2024 - AM,0059 - MRBR
3,,THU,13:00-13:50,BZ-01-079,,30,,
4,01A,THU,14:00-14:50 15:00-15:50,BZ-01-079 BZ-01-079,L L B B L L B B,30 30,Y 31/01/2024 - AM,0059 - MRBR
5,02,MON,12:00-12:50,BZ-02-106,,30,Y 31/01/2024 - AM,0059 - MRBR
6,,THU,08:00-08:50,BZ-01-079,,30,,
7,02A,THU,09:00-09:50 10:00-10:50,BZ-01-079 BZ-01-079,,30 30,Y 31/01/2024 - AM,0059 - MRBR
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
10,01 MON,,12:00-12:50,BZ-02-105,,60,Y Y 02/07/2024 - PM,0059 - MRBR
11,,,,,,,,
12,01A,THU,14:00-14:50 15:00-15:50 16:00-16:50,BZ-02-059 BZ-02-059 BZ-02-059,L B B B B B B,30 30 30,02/07/2024 - PM,0059 - MRBR
13,01B,THU,08:00-08:50 09:00-09:50 10:00-10:50,BZ-02-059 BZ-02-059 BZ-02-059,,30 30 30,Y 02/07/2024 - PM,0059 - MRBR

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,THU,08:00-08:50 14:00-14:50,BZ-02-059 BZ-02-100,,30 30,Y 06/02/2024 - PM,0882 - RNBR
3,01A,THU,09:00-09:50 10:00-10:50,BZ-02-059 BZ-02-059,,30 30,Y 06/02/2024 - PM,0882 - RNBR
4,03,THU,15:00-15:50,BZ-02-100,,30,Y 06/02/2024 - PM,0882 - RNBR
5,,WED,12:00-12:50,BZ-01-079,L L B B L L B B L L B B,30,,
6,03A,WED,13:00-13:50 14:00-14:50,BZ-01-079 BZ-01-079,,30 30,Y 06/02/2024 - PM,0882 - RNBR
7,04,MON,12:00-12:50,BZ-01-079,,30,Y 06/02/2024 - PM,0882 - RNBR
8,,THU,15:00-15:50,BZ-02-100,,30,,
9,04A,MON,13:00-13:50 14:00-14:50,BZ-01-079 BZ-01-079,,30 30,Y 06/02/2024 - PM,0882 - RNBR
10,Semester II Academic Session 2023/2024,,,,,,,
11,Sec Day Time Loc Mode Cap Exam Staff,,,,,,,
12,Y Y 01 MON 12:00-12:50 BZ-02-100 30 28/06/2024...,,,,,,,
13,L B B B 01A THU 12:00-12:50 BZ-01-079 30 28/06...,,,,,,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,THU,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 26/01/2024 - PM,01195 - MHBMH
3,01A,THU,16:00-16:50 17:00-17:50,BZ-03-093 BZ-03-093,,30 30,Y 26/01/2024 - PM,01195 - MHBMH
4,01B,THU,14:00-14:50 15:00-15:50,BZ-03-093 BZ-03-093,,30 30,Y 26/01/2024 - PM,01195 - MHBMH
5,03,MON,14:00-14:50 15:00-15:50,BZ-02-096 BZ-02-096,,60 60,Y 26/01/2024 - PM,01195 - MHBMH
6,03A,TUE,08:00-08:50 09:00-09:50,BZ-04-068 BZ-04-068,L L B B B B L L B B B B L L B B B B,30 30,Y 26/01/2024 - PM,01195 - MHBMH
7,03B,TUE,10:00-10:50 11:00-11:50,BZ-03-093 BZ-03-093,,30 30,Y 26/01/2024 - PM,0867 - KBAR
8,04,THU,14:00-14:50 15:00-15:50,BZ-02-096 BZ-02-096,,60 60,Y 26/01/2024 - PM,0867 - KBAR
9,04A,THU,08:00-08:50 09:00-09:50,BZ-04-068 BZ-04-068,,30 30,Y 26/01/2024 - PM,0867 - KBAR
10,04B,THU,10:00-10:50 11:00-11:50,BZ-03-093 BZ-03-093,,30 30,Y 26/01/2024 - PM,0867 - KBAR
11,Semester II Academic Session 2023/2024,,,,,,,
12,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
13,01,MON,14:00-14:50 15:00-15:50,BZ-01-124 BZ-01-124,,60 60,Y 27/06/2024 - PM,02016 - AMBJ
14,01A,TUE,08:00-08:50 09:00-09:50,BZ-03-093 BZ-03-093,,30 30,Y 27/06/2024 - PM,02016 - AMBJ
15,01B,TUE,10:00-10:50 11:00-11:50,BZ-03-093 BZ-03-093,,30 30,Y 27/06/2024 - PM,02016 - AMBJ
16,02,THU,14:00-14:50 15:00-15:50,BZ-01-124 BZ-01-124,,60 60,Y 27/06/2024 - PM,02016 - AMBJ
17,02A,THU,08:00-08:50 09:00-09:50,BZ-03-093 BZ-03-093,L L B B B B L L B B B B L L B B B B,30 30,Y 27/06/2024 - PM,FP0037 - SNBR
18,02B,THU,10:00-10:50 11:00-11:50,BZ-03-093 BZ-03-093,,30 30,Y 27/06/2024 - PM,FP0037 - SNBR
19,03,TUE,14:00-14:50 15:00-15:50,BZ-02-096 BZ-02-096,,60 60,Y 27/06/2024 - PM,FP0037 - SNBR
20,03A,WED,08:00-08:50 09:00-09:50,BZ-03-093 BZ-03-093,,30 30,Y 27/06/2024 - PM,FP0037 - SNBR
21,03B,TUE,16:00-16:50 17:00-17:50,BZ-03-093 BZ-03-093,,30 30,Y 27/06/2024 - PM,FP0037 - SNBR

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,16:00-16:50 17:00-17:50,BZ-02-096 BZ-02-096,,60 60,Y 06/02/2024 - AM,0027 - ZBM
3,01A,TUE,10:00-10:50 11:00-11:50,BZ-04-068 BZ-04-068,,30 30,Y 06/02/2024 - AM,0027 - ZBM
4,01B,THU,12:00-12:50 13:00-13:50,BZ-04-068 BZ-04-068,L L B B B B L L B B B B,30 30,Y 06/02/2024 - AM,0027 - ZBM
5,02,TUE,16:00-16:50 17:00-17:50,BZ-02-096 BZ-02-096,,60 60,Y 06/02/2024 - AM,0027 - ZBM
6,02A,WED,10:00-10:50 11:00-11:50,BZ-04-068 BZ-04-068,,30 30,Y 06/02/2024 - AM,0027 - ZBM
7,02B,WED,12:00-12:50 13:00-13:50,BZ-04-068 BZ-04-068,,30 30,Y 06/02/2024 - AM,0027 - ZBM
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
10,01,TUE,08:00-08:50 09:00-09:50,BZ-02-100 BZ-02-100,,60 60,Y 09/07/2024 - PM,0027 - ZBM
11,01A,MON,14:00-14:50 15:00-15:50,BZ-02-090 BZ-02-090,L L B B B B,30 30,Y 09/07/2024 - PM,0027 - ZBM
12,01B,MON,16:00-16:50 17:00-17:50,BZ-02-090 BZ-02-090,,30 30,Y 09/07/2024 - PM,0027 - ZBM

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,FRI,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,,30 30,N,0063 - ABA
3,01A,FRI,10:00-10:50 11:00-11:50,BZ-02-090 BZ-02-090,,30 30,N,0063 - ABA
4,02,MON,14:00-14:50 15:00-15:50,BZ-02-090 BZ-02-090,,30 30,N,01147 - KSBKI
5,02A,MON,16:00-16:50 17:00-17:50,BZ-02-090 BZ-02-090,L L B B L L B B L L B B L L B B,30 30,N,01147 - KSBKI
6,03,WED,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,,30 30,N,0063 - ABA
7,03A,WED,10:00-10:50 11:00-11:50,BZ-02-090 BZ-02-090,,30 30,N,0063 - ABA
8,04,MON,10:00-10:50 11:00-11:50,BZ-02-090 BZ-02-090,,30 30,N,0063 - ABA
9,04A,TUE,10:00-10:50 11:00-11:50,BZ-02-090 BZ-02-090,,30 30,N,01147 - KSBKI
10,Semester II Academic Session 2023/2024,,,,,,,
11,Sec Day Time Loc Mode Cap Exam Staff,,,,,,,
12,L L B B 01 WED 12:00-12:50 BZ-02-090 30 N 0044...,,,,,,,
13,01A TUE 08:00-08:50 BZ-02-090 30 N 0044 - RBAB...,,,,,,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,12:00-12:50 13:00-13:50,BZ-02-096 BZ-02-096,,60 60,Y 02/02/2024 - PM,0595 - ASBF
3,01A,THU,12:00-12:50 13:00-13:50,BZ-03-076 BZ-03-076,,30 30,Y 02/02/2024 - PM,01953 - NSBK
4,01B,THU,08:00-08:50 09:00-09:50,BZ-03-076 BZ-03-076,L L B B B B L L B B B B,30 30,Y 02/02/2024 - PM,01953 - NSBK
5,02,TUE,12:00-12:50 13:00-13:50,BZ-02-096 BZ-02-096,,60 60,Y 02/02/2024 - PM,01953 - NSBK
6,02A,WED,12:00-12:50 13:00-13:50,BZ-03-076 BZ-03-076,,29 29,Y 02/02/2024 - PM,01953 - NSBK
7,02B,WED,08:00-08:50 09:00-09:50,BZ-03-076 BZ-03-076,,25 25,Y 02/02/2024 - PM,01953 - NSBK
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
10,01,MON,12:00-12:50 13:00-13:50,BZ-02-106 BZ-02-106,,60 60,Y 26/06/2024 - AM,01891 - AFBMR
11,01A,THU,12:00-12:50 13:00-13:50,BZ-04-068 BZ-04-068,,30 30,Y 26/06/2024 - AM,01891 - AFBMR
12,01B,THU,08:00-08:50 09:00-09:50,BZ-04-068 BZ-04-068,,30 30,Y 26/06/2024 - AM,01891 - AFBMR
13,02,TUE,12:00-12:50 13:00-13:50,BZ-02-106 BZ-02-106,,60 60,Y 26/06/2024 - AM,01953 - NSBK
14,02A,WED,12:00-12:50 13:00-13:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - AM,01953 - NSBK
15,02B,WED,08:00-08:50 09:00-09:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - AM,01953 - NSBK
16,03,MON,16:00-16:50 17:00-17:50,BZ-02-106 BZ-02-106,L L B B B B L L B B B B L L B B B B L L B B B ...,60 60,Y 26/06/2024 - AM,0595 - ASBF
17,03A,TUE,10:00-10:50 11:00-11:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - AM,0595 - ASBF
18,03B,THU,12:00-12:50 13:00-13:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - AM,0595 - ASBF
19,04,TUE,16:00-16:50 17:00-17:50,BZ-02-106 BZ-02-106,,60 60,Y 26/06/2024 - AM,01195 - MHBMH
20,04A,WED,10:00-10:50 11:00-11:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - AM,01195 - MHBMH
21,04B,WED,12:00-12:50 13:00-13:50,BZ-04-068 BZ-04-068,,30 30,Y 26/06/2024 - AM,01195 - MHBMH
22,05,THU,16:00-16:50 17:00-17:50,BZ-02-106 BZ-02-106,,30 30,Y 26/06/2024 - AM,01195 - MHBMH
23,05A,THU,10:00-10:50 11:00-11:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - AM,01953 - NSBK

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap Exam Staff,,,,,,,
2,L L B B 01 WED 12:00-12:50 BZ-02-096 30 N 0177...,,,,,,,
3,01A TUE 12:00-12:50 BZ-02-090 30 N 01770 - ABM...,,,,,,,
4,Semester II Academic Session 2023/2024,,,,,,,
5,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
6,01,FRI,08:00-08:50 09:00-09:50,BZ-04-068 BZ-04-068,,30 30,N,0063 - ABA
7,01A,FRI,10:00-10:50 11:00-11:50,BZ-04-068 BZ-04-068,,30 30,N,0063 - ABA
8,02,MON,14:00-14:50 15:00-15:50,BZ-04-068 BZ-04-068,,30 30,N,0025 - RBM
9,02A,MON,16:00-16:50 17:00-17:50,BZ-04-068 BZ-04-068,,30 30,N,0025 - RBM
10,03,TUE,14:00-14:50 15:00-15:50,BZ-02-090 BZ-02-090,L L B B L L B B L L B B L L B B L L B B,30 30,N,01147 - KSBKI
11,03A,TUE,16:00-16:50 17:00-17:50,BZ-02-090 BZ-02-090,,30 30,N,01147 - KSBKI
12,04,THU,14:00-14:50 15:00-15:50,BZ-02-090 BZ-02-090,,30 30,N,01147 - KSBKI
13,04A,THU,16:00-16:50 17:00-17:50,BZ-02-090 BZ-02-090,,30 30,N,01147 - KSBKI
14,05,MON,08:00-08:50 09:00-09:50,BZ-04-068 BZ-04-068,,30 30,N,0063 - ABA
15,05A,MON,10:00-10:50 11:00-11:50,BZ-04-068 BZ-04-068,,30 30,N,0063 - ABA

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 25/01/2024 - PM,0132 - MABM@H
3,01A,FRI,10:00-10:50 11:00-11:50,BZ-04-085 BZ-04-085,,30 30,Y 25/01/2024 - PM,0132 - MABM@H
4,01B,FRI,08:00-08:50 09:00-09:50,BZ-04-085 BZ-04-085,,30 30,Y 25/01/2024 - PM,0132 - MABM@H
5,02,TUE,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 25/01/2024 - PM,0132 - MABM@H
6,02A,MON,16:00-16:50 17:00-17:50,BZ-04-085 BZ-04-085,L L B B B B L L B B B B L L B B B B,30 30,Y 25/01/2024 - PM,0132 - MABM@H
7,02B,MON,14:00-14:50 15:00-15:50,BZ-01-100 BZ-01-100,,30 30,Y 25/01/2024 - PM,0132 - MABM@H
8,03,WED,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 25/01/2024 - PM,01802 - AFBAN
9,03A,TUE,16:00-16:50 17:00-17:50,BZ-04-085 BZ-04-085,,30 30,Y 25/01/2024 - PM,01802 - AFBAN
10,03B,TUE,14:00-14:50 15:00-15:50,BZ-02-086 BZ-02-086,,30 30,Y 25/01/2024 - PM,01802 - AFBAN
11,Semester II Academic Session 2023/2024,,,,,,,
12,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
13,01,MON,10:00-10:50 11:00-11:50,BZ-02-106 BZ-02-106,,60 60,Y 27/06/2024 - AM,0132 - MABM@H
14,01A,FRI,10:00-10:50 11:00-11:50,BZ-04-085 BZ-04-085,,30 30,Y 27/06/2024 - AM,0132 - MABM@H
15,01B,FRI,08:00-08:50 09:00-09:50,BZ-04-085 BZ-04-085,,30 30,Y 27/06/2024 - AM,0132 - MABM@H
16,02,TUE,10:00-10:50 11:00-11:50,BZ-02-106 BZ-02-106,,60 60,Y 27/06/2024 - AM,01802 - AFBAN
17,02A,MON,16:00-16:50 17:00-17:50,BZ-04-077 BZ-04-077,L L B B B B L L B B B B L L B B B B,30 30,Y 27/06/2024 - AM,01802 - AFBAN
18,02B,MON,14:00-14:50 15:00-15:50,BZ-04-077 BZ-04-077,,30 30,Y 27/06/2024 - AM,01802 - AFBAN
19,03,WED,10:00-10:50 11:00-11:50,BZ-02-106 BZ-02-106,,60 60,Y 27/06/2024 - AM,0132 - MABM@H
20,03A,TUE,16:00-16:50 17:00-17:50,BZ-04-077 BZ-04-077,,30 30,Y 27/06/2024 - AM,0132 - MABM@H
21,03B,TUE,14:00-14:50 15:00-15:50,BZ-04-077 BZ-04-077,,30 30,Y 27/06/2024 - AM,0132 - MABM@H

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,08:00-08:50 09:00-09:50,BZ-02-105 BZ-02-105,,60 60,N,01862 - DNAEP
3,01A,TUE,14:00-14:50 15:00-15:50,BZ-03-051 BZ-03-051,,30 30,N,01862 - DNAEP
4,01B,TUE,16:00-16:50 17:00-17:50,BZ-03-051 BZ-03-051,L L B B B B L L B B,30 30,N,01862 - DNAEP
5,02,FRI,08:00-08:50 09:00-09:50,BZ-02-106 BZ-02-106,,30 30,N,01842 - NSABZ
6,02A,MON,08:00-08:50 09:00-09:50,BZ-03-051 BZ-03-051,,30 30,N,01842 - NSABZ
7,Semester II Academic Session 2023/2024,,,,,,,
8,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
9,01,THU,12:00-12:50 13:00-13:50,BZ-02-100 BZ-02-100,,60 60,N,01862 - DNAEP
10,01A,MON,12:00-12:50 13:00-13:50,BZ-03-051 BZ-03-051,,30 30,N,01862 - DNAEP
11,01B,MON,08:00-08:50 09:00-09:50,BZ-03-051 BZ-03-051,L L B B B B L L B B,30 30,N,01862 - DNAEP
12,02,WED,12:00-12:50 13:00-13:50,BZ-02-100 BZ-02-100,,30 30,N,01842 - NSABZ
13,02A,TUE,12:00-12:50 13:00-13:50,BZ-03-051 BZ-03-051,,30 30,N,01842 - NSABZ

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,08:00-08:50 09:00-09:50,BZ-01-121 BZ-01-121,,60 60,Y 30/01/2024 - AM,0161 - ABMS
3,01A,FRI,08:00-08:50 09:00-09:50,BZ-03-064 BZ-03-064,,30 30,Y 30/01/2024 - AM,0161 - ABMS
4,01B,FRI,10:00-10:50 11:00-11:50,BZ-03-064 BZ-03-064,,30 30,Y 30/01/2024 - AM,0161 - ABMS
5,02,TUE,08:00-08:50 09:00-09:50,BZ-01-124 BZ-01-124,,60 60,Y 30/01/2024 - AM,0161 - ABMS
6,02A,MON,14:00-14:50 15:00-15:50,BZ-03-064 BZ-03-064,L L B B B B L L B B B B L L B B B B,30 30,Y 30/01/2024 - AM,0161 - ABMS
7,02B,MON,16:00-16:50 17:00-17:50,BZ-03-064 BZ-03-064,,30 30,Y 30/01/2024 - AM,0161 - ABMS
8,03,FRI,08:00-08:50 09:00-09:50,BZ-01-124 BZ-01-124,,60 60,Y 30/01/2024 - AM,0153 - N@KBMN
9,03A,MON,08:00-08:50 09:00-09:50,BZ-03-064 BZ-03-064,,30 30,Y 30/01/2024 - AM,0153 - N@KBMN
10,03B,MON,10:00-10:50 11:00-11:50,BZ-03-064 BZ-03-064,,30 30,Y 30/01/2024 - AM,0161 - ABMS
11,Semester II Academic Session 2023/2024,,,,,,,
12,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
13,01,MON,08:00-08:50 09:00-09:50,BZ-02-096 BZ-02-096,,60 60,Y 28/06/2024 - AM,01309 - WNBWM
14,01A,FRI,08:00-08:50 09:00-09:50,BZ-03-064 BZ-03-064,,30 30,Y 28/06/2024 - AM,01309 - WNBWM
15,01B,FRI,10:00-10:50 11:00-11:50,BZ-03-064 BZ-03-064,,30 30,Y 28/06/2024 - AM,01309 - WNBWM
16,02,TUE,08:00-08:50 09:00-09:50,BZ-02-106 BZ-02-106,L L B B B B L L B B B B L L B B,60 60,Y 28/06/2024 - AM,01367 - SABMS
17,02A,MON,14:00-14:50 15:00-15:50,BZ-03-064 BZ-03-064,,30 30,Y 28/06/2024 - AM,01367 - SABMS
18,02B,MON,16:00-16:50 17:00-17:50,BZ-03-064 BZ-03-064,,30 30,Y 28/06/2024 - AM,01898 - SBIH
19,03,FRI,08:00-08:50 09:00-09:50,BZ-02-106 BZ-02-106,,30 30,Y 28/06/2024 - AM,01982 - ZBI
20,03B,MON,10:00-10:50 11:00-11:50,BZ-03-064 BZ-03-064,,30 30,Y 28/06/2024 - AM,01982 - ZBI

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,FRI,10:00-10:50 11:00-11:50,BZ-02-101 BZ-02-101,,30 30,Y 30/01/2024 - PM,01367 - SABMS
3,01A,MON,10:00-10:50 11:00-11:50,BZ-04-056 BZ-04-056,,30 30,Y 30/01/2024 - PM,01367 - SABMS
4,02,TUE,10:00-10:50 11:00-11:50,BZ-02-101 BZ-02-101,L L B B L L B B B B,60 60,Y 30/01/2024 - PM,01367 - SABMS
5,02A,MON,16:00-16:50 17:00-17:50,BZ-04-056 BZ-04-056,,30 30,Y 30/01/2024 - PM,01367 - SABMS
6,02B,MON,14:00-14:50 15:00-15:50,BZ-04-056 BZ-04-056,,30 30,Y 30/01/2024 - PM,01367 - SABMS
7,Semester II Academic Session 2023/2024,,,,,,,
8,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
9,01,FRI,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 05/07/2024 - PM,01367 - SABMS
10,01A,MON,10:00-10:50 11:00-11:50,BZ-04-056 BZ-04-056,L L B B B B,30 30,Y 05/07/2024 - PM,01367 - SABMS
11,01B,TUE,12:00-12:50 13:00-13:50,BZ-04-056 BZ-04-056,,30 30,Y 05/07/2024 - PM,01367 - SABMS

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,TUE,12:00-12:50 13:00-13:50,BZ-02-106 BZ-02-106,,60 60,Y 05/02/2024 - PM,01990 - HWS
3,01A,WED,12:00-12:50 13:00-13:50,BZ-03-069 BZ-03-069,L L B B B B,30 30,Y 05/02/2024 - PM,01990 - HWS
4,01B,WED,08:00-08:50 09:00-09:50,BZ-03-069 BZ-03-069,,30 30,Y 05/02/2024 - PM,01990 - HWS
5,Semester II Academic Session 2023/2024,,,,,,,
6,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
7,01,FRI,10:00-10:50 11:00-11:50,BZ-02-106 BZ-02-106,,60 60,Y 28/06/2024 - PM,01919 - SBAB
8,01A,MON,10:00-10:50 11:00-11:50,BZ-02-059 BZ-02-059,,30 30,Y 28/06/2024 - PM,S1286 - MR
9,01B,TUE,12:00-12:50 13:00-13:50,BZ-02-059 BZ-02-059,L L B B B B L L B B B B,30 30,Y 28/06/2024 - PM,01919 - SBAB
10,02,MON,16:00-16:50 17:00-17:50,BZ-01-127 BZ-01-127,,60 60,Y 28/06/2024 - PM,01919 - SBAB
11,02A,TUE,10:00-10:50 11:00-11:50,BZ-04-056 BZ-04-056,,30 30,Y 28/06/2024 - PM,S1286 - MR
12,02B,THU,12:00-12:50 13:00-13:50,BZ-04-056 BZ-04-056,,30 30,Y 28/06/2024 - PM,01919 - SBAB

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,12:00-12:50 13:00-13:50,BZ-01-121 BZ-01-121,,60 60,N,01868 - AFBZA
3,01A,TUE,12:00-12:50 13:00-13:50,BZ-02-059 BZ-02-059,L L B B B B,30 30,N,01868 - AFBZA
4,01B,TUE,08:00-08:50 09:00-09:50,BZ-04-056 BZ-04-056,,30 30,N,01868 - AFBZA
5,Semester II Academic Session 2023/2024,,,,,,,
6,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
7,01,MON,08:00-08:50 09:00-09:50,BZ-02-105 BZ-02-105,,30 30,N,01868 - AFBZA
8,01A,FRI,08:00-08:50 09:00-09:50,BZ-04-056 BZ-04-056,,30 30,N,01868 - AFBZA
9,02,TUE,08:00-08:50 09:00-09:50,BZ-02-105 BZ-02-105,L L B B L L B B B B,60 60,N,01868 - AFBZA
10,02A,MON,14:00-14:50 15:00-15:50,BZ-04-056 BZ-04-056,,30 30,N,01868 - AFBZA
11,02B,MON,16:00-16:50 17:00-17:50,BZ-04-056 BZ-04-056,,30 30,N,01868 - AFBZA

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,FRI,10:00-10:50 11:00-11:50,BZ-02-096 BZ-02-096,,60 60,Y 31/01/2024 - PM,0153 - N@KBMN
3,01A,MON,10:00-10:50 11:00-11:50,BZ-03-069 BZ-03-069,L L B B B B,30 30,Y 31/01/2024 - PM,0153 - N@KBMN
4,01B,TUE,12:00-12:50 13:00-13:50,BZ-03-069 BZ-03-069,,30 30,Y 31/01/2024 - PM,0153 - N@KBMN
5,Semester II Academic Session 2023/2024,,,,,,,
6,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
7,01,TUE,12:00-12:50 13:00-13:50,BZ-04-087 BZ-04-087,,30 30,Y 08/07/2024 - AM,0153 - N@KBMN
8,01A,WED,12:00-12:50 13:00-13:50,BZ-03-069 BZ-03-069,,30 30,Y 08/07/2024 - AM,0153 - N@KBMN
9,02,THU,12:00-12:50 13:00-13:50,BZ-04-087 BZ-04-087,L L B B L L B B B B,60 60,Y 08/07/2024 - AM,0153 - N@KBMN
10,02A,MON,12:00-12:50 13:00-13:50,BZ-03-069 BZ-03-069,,30 30,Y 08/07/2024 - AM,0153 - N@KBMN
11,02B,MON,08:00-08:50 09:00-09:50,BZ-03-069 BZ-03-069,,30 30,Y 08/07/2024 - AM,0153 - N@KBMN

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,10:00-10:50 11:00-11:50,BZ-01-124 BZ-01-124,,60 60,Y 06/02/2024 - AM,01863 - WISBWD
3,01A,FRI,10:00-10:50 11:00-11:50,BZ-04-063 BZ-04-063,,30 30,Y 06/02/2024 - AM,01863 - WISBWD
4,01B,FRI,08:00-08:50 09:00-09:50,BZ-04-063 BZ-04-063,L L B B B B L L B B B B,30 30,Y 06/02/2024 - AM,01863 - WISBWD
5,02,TUE,10:00-10:50 11:00-11:50,BZ-01-124 BZ-01-124,,60 60,Y 06/02/2024 - AM,01863 - WISBWD
6,02A,MON,16:00-16:50 17:00-17:50,BZ-04-063 BZ-04-063,,30 30,Y 06/02/2024 - AM,01863 - WISBWD
7,02B,MON,14:00-14:50 15:00-15:50,BZ-04-063 BZ-04-063,,30 30,Y 06/02/2024 - AM,01863 - WISBWD
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
10,01,MON,10:00-10:50 11:00-11:50,BZ-01-121 BZ-01-121,,60 60,Y 02/07/2024 - AM,01863 - WISBWD
11,01A,FRI,10:00-10:50 11:00-11:50,BZ-04-063 BZ-04-063,L L B B B B,30 30,Y 02/07/2024 - AM,01863 - WISBWD
12,01B,FRI,08:00-08:50 09:00-09:50,BZ-04-063 BZ-04-063,,30 30,Y 02/07/2024 - AM,01863 - WISBWD

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,14:00-14:50,BZ-02-106,,30,31/01/2024 - AM Y,0198 - SBN
3,,TUE,08:00-08:50,BZ-02-059,,30,,
4,01A,TUE,09:00-09:50 10:00-10:50,BZ-02-059 BZ-02-059,L L B B L L B B,30 30,31/01/2024 - AM Y,0198 - SBN
5,02,MON,14:00-14:50,BZ-02-106,,30,31/01/2024 - AM Y,0198 - SBN
6,,WED,08:00-08:50,BZ-01-079,,30,,
7,02A,WED,09:00-09:50 10:00-10:50,BZ-01-079 BZ-01-079,,30 30,31/01/2024 - AM Y,0198 - SBN
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
10,WED 01,,10:00-10:50,BZ-01-121,,60,Y Y 03/07/2024 - PM,01863 - WISBWD
11,,,,,,,,
12,01A,TUE,14:00-14:50 15:00-15:50 16:00-16:50,BZ-01-079 BZ-01-079 BZ-01-079,L B B B B B B,30 30 30,03/07/2024 - PM,01863 - WISBWD
13,01B,THU,15:00-15:50 16:00-16:50 17:00-17:50,BZ-01-079 BZ-01-079 BZ-01-079,,30 30 30,03/07/2024 - PM Y,01863 - WISBWD

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
2,01,MON,12:00-12:50 13:00-13:50,BZ-01-124 BZ-01-124,,50 50,05/02/2024 - AM Y,01984 - SSBAH
3,01A,THU,12:00-12:50 13:00-13:50,BZ-03-093 BZ-03-093,,30 30,05/02/2024 - AM Y,01984 - SSBAH
4,01B,THU,08:00-08:50 09:00-09:50,BZ-03-093 BZ-03-093,,20 20,05/02/2024 - AM Y,01984 - SSBAH
5,02,TUE,12:00-12:50 13:00-13:50,BZ-01-124 BZ-01-124,,60 60,05/02/2024 - AM Y,01984 - SSBAH
6,02A,WED,12:00-12:50 13:00-13:50,BZ-03-093 BZ-03-093,L L B B B B L L B B B B L L B B B B,30 30,05/02/2024 - AM Y,01984 - SSBAH
7,02B,WED,08:00-08:50 09:00-09:50,BZ-03-093 BZ-03-093,,30 30,05/02/2024 - AM Y,01890 - NSBAR
8,03,WED,12:00-12:50 13:00-13:50,BZ-02-101 BZ-02-101,,41 41,05/02/2024 - AM Y,01890 - NSBAR
9,03A,TUE,12:00-12:50 13:00-13:50,BZ-03-093 BZ-03-093,,27 27,05/02/2024 - AM Y,01890 - NSBAR
10,03B,TUE,08:00-08:50 09:00-09:50,BZ-03-093 BZ-03-093,,11 11,05/02/2024 - AM Y,01890 - NSBAR
11,Semester II Academic Session 2023/2024,,,,,,,
12,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
13,01,THU,12:00-12:50 13:00-13:50,BZ-01-124 BZ-01-124,,60 60,09/07/2024 - AM Y,01984 - SSBAH
14,01A,MON,12:00-12:50 13:00-13:50,BZ-03-093 BZ-03-093,,30 30,09/07/2024 - AM Y,01984 - SSBAH
15,01B,MON,08:00-08:50 09:00-09:50,BZ-03-093 BZ-03-093,L L B B B B L L B B,30 30,09/07/2024 - AM Y,01984 - SSBAH
16,02,WED,12:00-12:50 13:00-13:50,BZ-01-124 BZ-01-124,,30 30,09/07/2024 - AM Y,0543 - RBMS
17,02B,TUE,08:00-08:50 09:00-09:50,BZ-01-092 BZ-01-092,,30 30,09/07/2024 - AM Y,01984 - SSBAH

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,08:00-08:50 09:00-09:50,BZ-02-106 BZ-02-106,,60 60,Y 29/01/2024 - PM,0044 - RBAB
3,01A,TUE,14:00-14:50 15:00-15:50,BZ-02-090 BZ-02-090,,30 30,Y 29/01/2024 - PM,0044 - RBAB
4,01B,TUE,16:00-16:50 17:00-17:50,BZ-02-090 BZ-02-090,L L B B B B L L B B B B,30 30,Y 29/01/2024 - PM,0044 - RBAB
5,02,THU,08:00-08:50 09:00-09:50,BZ-02-106 BZ-02-106,,60 60,Y 29/01/2024 - PM,01453 - ABZ
6,02A,THU,14:00-14:50 15:00-15:50,BZ-02-090 BZ-02-090,,30 30,Y 29/01/2024 - PM,01453 - ABZ
7,02B,THU,16:00-16:50 17:00-17:50,BZ-02-090 BZ-02-090,,30 30,Y 29/01/2024 - PM,01453 - ABZ
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
10,01,MON,16:00-16:50 17:00-17:50,BZ-02-101 BZ-02-101,,60 60,Y 05/07/2024 - PM,01453 - ABZ
11,01A,WED,14:00-14:50 15:00-15:50,BZ-04-068 BZ-04-068,L L B B B B,30 30,Y 05/07/2024 - PM,01453 - ABZ
12,01B,MON,12:00-12:50 13:00-13:50,BZ-04-068 BZ-04-068,,30 30,Y 05/07/2024 - PM,01453 - ABZ

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,16:00-16:50 17:00-17:50,BZ-02-100 BZ-02-100,,60 60,N,0543 - RBMS
3,01A,TUE,10:00-10:50 11:00-11:50,BZ-01-092 BZ-01-092,,30 30,N,0543 - RBMS
4,01B,THU,12:00-12:50 13:00-13:50,BZ-01-092 BZ-01-092,L L B B B B L L B B B B,30 30,N,0543 - RBMS
5,02,MON,10:00-10:50 11:00-11:50,BZ-04-087 BZ-04-087,,60 60,N,0025 - RBM
6,02A,FRI,10:00-10:50 11:00-11:50,BZ-03-076 BZ-03-076,,30 30,N,0025 - RBM
7,02B,FRI,08:00-08:50 09:00-09:50,BZ-03-076 BZ-03-076,,30 30,N,0543 - RBMS
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
10,01,TUE,14:00-14:50 15:00-15:50,BZ-01-121 BZ-01-121,,60 60,N,0543 - RBMS
11,01A,WED,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,L L B B B B,30 30,N,0543 - RBMS
12,01B,WED,10:00-10:50 11:00-11:50,BZ-02-090 BZ-02-090,,30 30,N,0543 - RBMS

                                                   0
0              Semester I Academic Session 2023/2024
1               Sec Day Time Loc Mode Cap Exam Staff
2  L L B B 01 WED 08:00-08:50 BZ-02-100 32 Y 25/0...
3  01A MON 08:00-08:50 BZ-03-083 32 Y 25/01/2024 ...

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,10:00-10:50 11:00-11:50,BZ-01-124 BZ-01-124,,60 60,Y 25/01/2024 - AM,01801 - KAM
3,01A,TUE,16:00-16:50 17:00-17:50,BZ-04-077 BZ-04-077,,30 30,Y 25/01/2024 - AM,01801 - KAM
4,01B,TUE,14:00-14:50 15:00-15:50,BZ-04-077 BZ-04-077,,30 30,Y 25/01/2024 - AM,01801 - KAM
5,02,THU,10:00-10:50 11:00-11:50,BZ-01-121 BZ-01-121,,60 60,Y 25/01/2024 - AM,01801 - KAM
6,02A,THU,16:00-16:50 17:00-17:50,BZ-04-077 BZ-04-077,,30 30,Y 25/01/2024 - AM,01801 - KAM
7,02B,THU,14:00-14:50 15:00-15:50,BZ-04-077 BZ-04-077,L L B B B B L L B B B B L L B B B B L L B B B B,30 30,Y 25/01/2024 - AM,01801 - KAM
8,03,MON,08:00-08:50 09:00-09:50,BZ-02-104 BZ-02-104,,60 60,Y 25/01/2024 - AM,0145 - WMSBWH
9,03A,FRI,08:00-08:50 09:00-09:50,BZ-04-077 BZ-04-077,,30 30,Y 25/01/2024 - AM,0145 - WMSBWH
10,03B,FRI,10:00-10:50 11:00-11:50,BZ-04-077 BZ-04-077,,30 30,Y 25/01/2024 - AM,0145 - WMSBWH
11,04,TUE,08:00-08:50 09:00-09:50,BZ-02-104 BZ-02-104,,60 60,Y 25/01/2024 - AM,0145 - WMSBWH
12,04A,MON,14:00-14:50 15:00-15:50,BZ-04-077 BZ-04-077,,30 30,Y 25/01/2024 - AM,0145 - WMSBWH
13,04B,MON,16:00-16:50 17:00-17:50,BZ-04-077 BZ-04-077,,30 30,Y 25/01/2024 - AM,0145 - WMSBWH
14,Semester II Academic Session 2023/2024,,,,,,,
15,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
16,01,MON,08:00-08:50 09:00-09:50,BZ-01-124 BZ-01-124,,60 60,Y 04/07/2024 - AM,0145 - WMSBWH
17,01A,FRI,08:00-08:50 09:00-09:50,BZ-04-077 BZ-04-077,,30 30,Y 04/07/2024 - AM,0145 - WMSBWH
18,01B,FRI,10:00-10:50 11:00-11:50,BZ-04-077 BZ-04-077,L L B B B B L L B B,30 30,Y 04/07/2024 - AM,0145 - WMSBWH
19,02,TUE,08:00-08:50 09:00-09:50,BZ-01-124 BZ-01-124,,30 30,Y 04/07/2024 - AM,0145 - WMSBWH
20,02A,MON,14:00-14:50 15:00-15:50,BZ-04-077 BZ-04-077,,30 30,Y 04/07/2024 - AM,0145 - WMSBWH

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,08A,THU,11:00-11:50 12:00-12:50,E10-F06A E10-F06A,,30 30,N,02052 - NSBMN
3,08B,THU,11:00-11:50 12:00-12:50,E10-F06A E10-F06A,,30 30,N,02052 - NSBMN
4,08P,WED,08:00-08:50 09:00-09:50,E20BT1 E20BT1,,40 40,N,02052 - NSBMN
5,09A,WED,10:00-10:50 11:00-11:50,E10-F06A E10-F06A,,20 20,N,02052 - NSBMN
6,09B,WED,10:00-10:50 11:00-11:50,E10-F06A E10-F06A,,20 20,N,02052 - NSBMN
7,09P,MON,10:00-10:50 11:00-11:50,E22BK6 E22BK6,B B B B L L B B B B L L B B B B L L B B B B L L,40 40,N,02052 - NSBMN
8,10A,THU,10:00-10:50 11:00-11:50,BZ-02-080 BZ-02-080,,30 30,N,S1287 - NAFBZ
9,10B,THU,10:00-10:50 11:00-11:50,BZ-02-080 BZ-02-080,,30 30,N,S1287 - NAFBZ
10,10P,TUE,10:00-10:50 11:00-11:50,BZ-02-100 BZ-02-100,,60 60,N,S1287 - NAFBZ
11,11A,WED,16:00-16:50 17:00-17:50,BZ-01-100 BZ-01-100,,30 30,N,01802 - AFBAN
12,11B,WED,16:00-16:50 17:00-17:50,BZ-01-100 BZ-01-100,,30 30,N,01802 - AFBAN
13,11P,MON,16:00-16:50 17:00-17:50,BZ-01-124 BZ-01-124,,60 60,N,01802 - AFBAN
14,Semester II Academic Session 2023/2024,,,,,,,
15,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
16,10A,THU,12:00-12:50 13:00-13:50,E00-F01 E00-F01,,30 30,N,FP0039 - NIHBMF
17,10B,THU,12:00-12:50 13:00-13:50,E00-F01 E00-F01,,30 30,N,FP0039 - NIHBMF
18,10P,TUE,12:00-12:50 13:00-13:50,E00-F01 E00-F01,,0 0 3,N,FP0039 - NIHBMF
19,11A,WED,16:00-16:50 17:00-17:50,BZ-01-100 BZ-01-100,B B B B L L B B B B L L B B L L,0 30,N,FP0041 - ABI
20,11B,WED,16:00-16:50 17:00-17:50,BZ-01-100 BZ-01-100,,30 30,N,FP0041 - ABI
21,11P,MON,16:00-16:50 17:00-17:50,FKP-F-DK-01 FKP-F-DK-01,,60 60,N,FP0041 - ABI
22,14A,WED,14:00-14:50 15:00-15:50,BZ-03-083 BZ-03-083,,30 30,N,0027 - ZBM
23,14P,MON,14:00-14:50 15:00-15:50,BZ-01-107 BZ-01-107,,30 30,N,0053 - TABAK

                                                   0
0              Semester I Academic Session 2023/2024
1               Sec Day Time Loc Mode Cap Exam Staff
2  L L B B 01 FRI 10:00-10:50 BZ-01-124 30 Y 2623...
3  01A TUE 12:00-12:50 BZ-02-080 30 Y 2623 - MAK ...

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,10:00-10:50 11:00-11:50,BZ-02-105 BZ-02-105,,90 90,N,01988 - NFBMR
3,01A,TUE,16:00-16:50 17:00-17:50,BZ-01-107 BZ-01-107,L L B B B B B B,30 30,N,01988 - NFBMR
4,01B,TUE,14:00-14:50 15:00-15:50,BZ-01-107 BZ-01-107,,30 30,N,2309 - FE
5,01C,THU,14:00-14:50 15:00-15:50,BZ-01-107 BZ-01-107,,30 30,N,2309 - FE
6,Semester II Academic Session 2023/2024,,,,,,,
7,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
8,01,THU,08:00-08:50 09:00-09:50,BZ-02-104 BZ-02-104,,90 90,N,01988 - NFBMR
9,01A,THU,16:00-16:50 17:00-17:50,BZ-01-107 BZ-01-107,L L B B B B B B,30 30,N,01988 - NFBMR
10,01B,THU,14:00-14:50 15:00-15:50,BZ-01-107 BZ-01-107,,30 30,N,01988 - NFBMR
11,01C,TUE,14:00-14:50 15:00-15:50,BZ-01-107 BZ-01-107,,30 30,N,01988 - NFBMR

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,08:00-08:50 09:00-09:50 10:00-10:50 11:00-11:5...,BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-...,L L L L L L L L L L,30 30 30 30 30 30 30 30 30 30,N,01933 - MIBMJ
3,Semester II Academic Session 2023/2024,,,,,,,
4,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
5,01,MON,08:00-08:50 09:00-09:50 10:00-10:50 11:00-11:5...,BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-...,L L L L L L L L L L,30 30 30 30 30 30 30 30 30 30,N,01933 - MIBMJ

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,TUE,08:00-08:50 09:00-09:50 10:00-10:50 11:00-11:5...,BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-...,L L L L L L L L L L,30 30 30 30 30 30 30 30 30 30,N,01923 - ABZ
3,Semester II Academic Session 2023/2024,,,,,,,
4,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
5,01,TUE,08:00-08:50 09:00-09:50 10:00-10:50 11:00-11:5...,BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-...,L L L L L L L L L,30 30 30 30 30 30 30 30 30,N,01923 - ABZ

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,THU,14:00-14:50 15:00-15:50,BZ-02-106 BZ-02-106,,60 60,N,0053 - TABAK
3,01A,MON,08:00-08:50 09:00-09:50,BZ-01-066 BZ-01-066,L L B B B B,30 30,N,0053 - TABAK
4,01B,MON,10:00-10:50 11:00-11:50,BZ-01-066 BZ-01-066,,30 30,N,0053 - TABAK
5,Semester II Academic Session 2023/2024,,,,,,,
6,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
7,01,THU,14:00-14:50 15:00-15:50,BZ-02-105 BZ-02-105,,60 60,N,0053 - TABAK
8,01A,THU,08:00-08:50 09:00-09:50,BZ-01-066 BZ-01-066,L L B B B B,30 30,N,0053 - TABAK
9,01B,THU,10:00-10:50 11:00-11:50,BZ-01-066 BZ-01-066,,30 30,N,0053 - TABAK

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,08:00-08:50 09:00-09:50,BZ-02-049 BZ-02-049,,30 30,N,01444 - ASBL
3,01A,TUE,14:00-14:50 15:00-15:50,BZ-02-049 BZ-02-049,L L B B L L B B,30 30,N,01444 - ASBL
4,02,THU,08:00-08:50 09:00-09:50,BZ-02-049 BZ-02-049,,30 30,N,01444 - ASBL
5,02A,THU,14:00-14:50 15:00-15:50,BZ-02-049 BZ-02-049,,30 30,N,01444 - ASBL
6,Semester II Academic Session 2023/2024,,,,,,,
7,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
8,01,TUE,14:00-14:50 15:00-15:50,BZ-03-051 BZ-03-051,,30 30,N,01444 - ASBL
9,01A,TUE,16:00-16:50 17:00-17:50,BZ-03-051 BZ-03-051,L L B B L L B B,30 30,N,01444 - ASBL
10,02,THU,14:00-14:50 15:00-15:50,BZ-03-051 BZ-03-051,,30 30,N,01444 - ASBL
11,02A,THU,16:00-16:50 17:00-17:50,BZ-03-051 BZ-03-051,,30 30,N,01444 - ASBL

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,THU,12:00-12:50 13:00-13:50,BZ-02-105 BZ-02-105,,60 60,Y 01/02/2024 - AM,2309 - FE
3,01A,MON,12:00-12:50 13:00-13:50,BZ-01-066 BZ-01-066,L L B B B B,30 30,Y 01/02/2024 - AM,2309 - FE
4,01C,WED,08:00-08:50 09:00-09:50,BZ-01-066 BZ-01-066,,30 30,Y 01/02/2024 - AM,2309 - FE
5,Semester II Academic Session 2023/2024,,,,,,,
6,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
7,01,THU,08:00-08:50 09:00-09:50,BZ-02-105 BZ-02-105,,60 60,Y 08/07/2024 - PM,2309 - FE
8,01A,THU,14:00-14:50 15:00-15:50,BZ-01-066 BZ-01-066,L L B B B B,30 30,Y 08/07/2024 - PM,2309 - FE
9,01B,THU,16:00-16:50 17:00-17:50,BZ-01-066 BZ-01-066,,30 30,Y 08/07/2024 - PM,2309 - FE

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,14:00-14:50 15:00-15:50,BZ-03-051 BZ-03-051,,30 30,N,0881 - BBY
3,01A,TUE,08:00-08:50 09:00-09:50,BZ-03-051 BZ-03-051,L L B B L L B B,30 30,N,0881 - BBY
4,02,TUE,14:00-14:50 15:00-15:50,BZ-03-060 BZ-03-060,,30 30,N,0881 - BBY
5,02A,WED,08:00-08:50 09:00-09:50,BZ-03-060 BZ-03-060,,30 30,N,0881 - BBY
6,Semester II Academic Session 2023/2024,,,,,,,
7,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
8,01,TUE,08:00-08:50 09:00-09:50,BZ-03-051 BZ-03-051,,30 30,N,0881 - BBY
9,01A,TUE,10:00-10:50 11:00-11:50,BZ-03-051 BZ-03-051,L L B B L L B B,30 30,N,0881 - BBY
10,02,WED,08:00-08:50 09:00-09:50,BZ-03-051 BZ-03-051,,30 30,N,0881 - BBY
11,02A,WED,10:00-10:50 11:00-11:50,BZ-03-051 BZ-03-051,,30 30,N,0881 - BBY

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,MON,14:00-14:50 15:00-15:50,BZ-02-104 BZ-02-104,,90 90,N,0064 - ABA
3,01A,TUE,08:00-08:50 09:00-09:50,BZ-02-049 BZ-02-049,L L B B B B B B,30 30,N,0064 - ABA
4,01B,TUE,10:00-10:50 11:00-11:50,BZ-02-049 BZ-02-049,,30 30,N,0064 - ABA
5,01C,FRI,08:00-08:50 09:00-09:50,BZ-02-049 BZ-02-049,,30 30,N,0064 - ABA
6,Semester II Academic Session 2023/2024,,,,,,,
7,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
8,01,TUE,10:00-10:50 11:00-11:50,BZ-02-104 BZ-02-104,,90 90,N,0064 - ABA
9,01A,MON,16:00-16:50 17:00-17:50,BZ-02-049 BZ-02-049,L L B B B B B B,30 30,N,0064 - ABA
10,01B,MON,10:00-10:50 11:00-11:50,BZ-02-049 BZ-02-049,,30 30,N,0064 - ABA
11,01C,TUE,08:00-08:50 09:00-09:50,BZ-02-049 BZ-02-049,,30 30,N,0064 - ABA

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,TUE,12:00-12:50 13:00-13:50,BZ-02-105 BZ-02-105,,90 90,N,01511 - RBM
3,01A,WED,12:00-12:50 13:00-13:50,BZ-03-051 BZ-03-051,L L B B B B B B,30 30,N,01511 - RBM
4,01B,WED,08:00-08:50 09:00-09:50,BZ-03-051 BZ-03-051,,30 30,N,01511 - RBM
5,01C,MON,12:00-12:50 13:00-13:50,BZ-03-051 BZ-03-051,,30 30,N,01511 - RBM
6,Semester II Academic Session 2023/2024,,,,,,,
7,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
8,01,TUE,12:00-12:50 13:00-13:50,BZ-02-104 BZ-02-104,,90 90,N,01511 - RBM
9,01A,WED,12:00-12:50 13:00-13:50,BZ-02-050 BZ-02-050,L L B B B B B B,30 30,N,01511 - RBM
10,01B,WED,08:00-08:50 09:00-09:50,BZ-02-050 BZ-02-050,,30 30,N,01511 - RBM
11,01C,THU,12:00-12:50 13:00-13:50,BZ-02-050 BZ-02-050,,30 30,N,01511 - RBM

                                                   0
0              Semester I Academic Session 2023/2024
1               Sec Day Time Loc Mode Cap Exam Staff
2  L L B B 01 MON 08:00-08:50 BZ-04-087 30 Y 31/0...
3  01A FRI 08:00-08:50 BZ-02-062 30 Y 31/01/2024 ...
4             Semester II Academic Session 2023/2024
5               Sec Day Time Loc Mode Cap Exam Staff
6  L L B B 01 MON 12:00-12:50 BZ-04-087 30 Y 02/0...
7  01A THU 12:00-12:50 BZ-02-062 30 Y 02/07/2024 ...

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,FRI,10:00-10:50 11:00-11:50,BZ-04-087 BZ-04-087,,60 60,N,0595 - ASBF
3,01A,MON,10:00-10:50 11:00-11:50,BZ-04-063 BZ-04-063,L L B B B B,30 30,N,0595 - ASBF
4,01B,TUE,12:00-12:50 13:00-13:50,BZ-04-063 BZ-04-063,,30 30,N,0595 - ASBF
5,Semester II Academic Session 2023/2024,,,,,,,
6,Sec Day Time Loc Mode Cap Exam Staff,,,,,,,
7,L L B B 01 TUE 14:00-14:50 BZ-04-087 30 N 0595...,,,,,,,
8,01A THU 10:00-10:50 BZ-02-090 30 N 0595 - ASBF...,,,,,,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,08:00-08:50 09:00-09:50 10:00-10:50 11:00-11:5...,BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-...,L L L L L L L L L L,30 30 30 30 30 30 30 30 30 30,N,01923 - ABZ
3,Semester II Academic Session 2023/2024,,,,,,,
4,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
5,01,WED,08:00-08:50 09:00-09:50 10:00-10:50 11:00-11:5...,BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-074 BZ-01-...,L L L L L L L L L L,30 30 30 30 30 30 30 30 30 30,N,01923 - ABZ

                                                   0
0              Semester I Academic Session 2023/2024
1               Sec Day Time Loc Mode Cap Exam Staff
2  L L T T Y 29/01/2024 - AM 01 TUE 08:00-08:50 B...
3  Y 29/01/2024 - AM 01A THU 08:00-08:50 BZ-01-09...

                                                   0
0              Semester I Academic Session 2023/2024
1               Exam Sec Day Time Loc Mode Cap Staff
2  L L B B Y 26/01/2024 - PM 01 TUE 14:00-14:50 B...
3  Y 26/01/2024 - PM 01A WED 10:00-10:50 BZ-03-09...
4             Semester II Academic Session 2023/2024
5               Exam Sec Day Time Loc Mode Cap Staff
6  L L B B Y 27/06/2024 - PM 01 WED 10:00-10:50 B...
7  Y 27/06/2024 - PM 01A MON 10:00-10:50 BZ-03-09...

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,12:00-12:50 13:00-13:50,BZ-01-124 BZ-01-124,,60 60,Y 07/02/2024 - AM,0159 - NBMA
3,01A,TUE,12:00-12:50 13:00-13:50,BZ-03-076 BZ-03-076,,30 30,Y 07/02/2024 - AM,0159 - NBMA
4,01B,TUE,08:00-08:50 09:00-09:50,BZ-03-076 BZ-03-076,L L B B B B L L B B B B,30 30,Y 07/02/2024 - AM,0159 - NBMA
5,02,THU,12:00-12:50 13:00-13:50,BZ-01-124 BZ-01-124,,60 60,Y 07/02/2024 - AM,0159 - NBMA
6,02A,MON,12:00-12:50 13:00-13:50,BZ-03-076 BZ-03-076,,30 30,Y 07/02/2024 - AM,01890 - NSBAR
7,02B,MON,08:00-08:50 09:00-09:50,BZ-03-076 BZ-03-076,,30 30,Y 07/02/2024 - AM,0159 - NBMA
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
10,01,WED,12:00-12:50 13:00-13:50,BZ-02-096 BZ-02-096,,60 60,Y 26/06/2024 - PM,0159 - NBMA
11,01A,TUE,12:00-12:50 13:00-13:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - PM,0159 - NBMA
12,01B,TUE,08:00-08:50 09:00-09:50,BZ-03-076 BZ-03-076,,30 30,Y 26/06/2024 - PM,0159 - NBMA
13,02,THU,12:00-12:50 13:00-13:50,BZ-02-096 BZ-02-096,,60 60,Y 26/06/2024 - PM,0159 - NBMA
14,02A,MON,12:00-12:50 13:00-13:50,BZ-02-090 BZ-02-090,,30 30,Y 26/06/2024 - PM,0159 - NBMA
15,02B,MON,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,,30 30,Y 26/06/2024 - PM,01985 - M'BM
16,03,MON,12:00-12:50 13:00-13:50,BZ-02-101 BZ-02-101,,60 60,Y 26/06/2024 - PM,01890 - NSBAR
17,03A,THU,12:00-12:50 13:00-13:50,BZ-01-092 BZ-01-092,L L B B B B L L B B B B L L B B B B L L B B B ...,30 30,Y 26/06/2024 - PM,01890 - NSBAR
18,03B,THU,08:00-08:50 09:00-09:50,BZ-01-092 BZ-01-092,,30 30,Y 26/06/2024 - PM,01890 - NSBAR
19,04,TUE,12:00-12:50 13:00-13:50,BZ-02-101 BZ-02-101,,60 60,Y 26/06/2024 - PM,01890 - NSBAR
20,04A,WED,12:00-12:50 13:00-13:50,BZ-01-092 BZ-01-092,,30 30,Y 26/06/2024 - PM,FP0038 - KAG
21,04B,WED,08:00-08:50 09:00-09:50,BZ-01-092 BZ-01-092,,30 30,Y 26/06/2024 - PM,FP0038 - KAG
22,05,MON,08:00-08:50 09:00-09:50,BZ-02-101 BZ-02-101,,60 60,Y 26/06/2024 - PM,FP0038 - KAG
23,05A,FRI,08:00-08:50 09:00-09:50,BZ-01-092 BZ-01-092,,30 30,Y 26/06/2024 - PM,FP0038 - KAG
24,05B,FRI,10:00-10:50 11:00-11:50,BZ-01-092 BZ-01-092,,30 30,Y 26/06/2024 - PM,FP0038 - KAG

,0,1,2,3,4,5,6
0,Semester I Academic Session 2023/2024,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,Exam,Staff
2,01 TUE,10:00-10:50 11:00-11:50,BZ-02-106 BZ-02-106,,60 60,N,01449 - MZTBA@TCL
3,,,,,,,
4,01A MON,16:00-16:50 17:00-17:50,BZ-01-092 BZ-01-092,,30 30,N,01449 - MZTBA@TCL
5,,,,,,,
6,01B MON,14:00-14:50 15:00-15:50,BZ-01-092 BZ-01-092,L L B B B B L L B B,30 30,N,01449 - MZTBA@TCL
7,,,,,,,
8,02 MON,08:00-08:50 09:00-09:50,BZ-02-100 BZ-02-100,,30 30,N,01443 - MIBUO
9,02A FRI,08:00-08:50 09:00-09:50,BZ-01-092 BZ-01-092,,30 30,N,01449 - MZTBA@TCL
10,,,,,,,
11,Semester II Academic Session 2023/2024,,,,,,
12,Sec Day Time Loc Mode Cap,,,,,Exam,Staff
13,01 TUE,10:00-10:50 11:00-11:50,BZ-02-105 BZ-02-105,,60 60,N,01449 - MZTBA@TCL
14,,,,,,,
15,01A MON,16:00-16:50 17:00-17:50,BZ-01-092 BZ-01-092,,30 30,N,01449 - MZTBA@TCL
16,,,,,,,
17,01B MON,14:00-14:50 15:00-15:50,BZ-01-092 BZ-01-092,L L B B B B L L B B,30 30,N,01449 - MZTBA@TCL
18,,,,,,,
19,02 MON,08:00-08:50 09:00-09:50,BZ-02-100 BZ-02-100,,30 30,N,01449 - MZTBA@TCL
20,,,,,,,
21,02A FRI,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,,30 30,N,01449 - MZTBA@TCL
22,,,,,,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
2,01,MON,10:00-10:50 11:00-11:50,BZ-05-027 BZ-05-027,,60 60,N,0043 - MBAM
3,01A,FRI,10:00-10:50 11:00-11:50,BZ-03-093 BZ-03-093,,30 30,N,0043 - MBAM
4,01B,FRI,08:00-08:50 09:00-09:50,BZ-03-093 BZ-03-093,L L B B B B L L B B B B,30 30,N,0043 - MBAM
5,02,TUE,08:00-08:50 09:00-09:50,BZ-05-027 BZ-05-027,,60 60,N,0121 - JBS
6,02A,MON,14:00-14:50 15:00-15:50,BZ-03-093 BZ-03-093,,30 30,N,0121 - JBS
7,02B,MON,16:00-16:50 17:00-17:50,BZ-03-093 BZ-03-093,,30 30,N,0043 - MBAM
8,Semester II Academic Session 2023/2024,,,,,,,
9,Sec Day Time Loc Mode Cap Exam Staff,,,,,,,
10,L L B B 01 N MON 10:00-10:50 BZ-05-027 60 0019...,,,,,,,
11,01A N FRI 10:00-10:50 BZ-05-027 60 0019 - ABK ...,,,,,,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,TUE,08:00-08:50 09:00-09:50,BZ-02-096 BZ-02-096,,30 30,Y 07/02/2024 - PM,01770 - ABMA
3,01A,MON,14:00-14:50 15:00-15:50,BZ-03-076 BZ-03-076,,30 30,Y 07/02/2024 - PM,01770 - ABMA
4,02,THU,12:00-12:50 13:00-13:50,BZ-02-096 BZ-02-096,L L B B L L B B B B,60 60,Y 07/02/2024 - PM,01147 - KSBKI
5,02A,MON,12:00-12:50 13:00-13:50,BZ-02-090 BZ-02-090,,30 30,Y 07/02/2024 - PM,01770 - ABMA
6,02B,MON,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,,30 30,Y 07/02/2024 - PM,01147 - KSBKI
7,Semester II Academic Session 2023/2024,,,,,,,
8,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
9,01,MON,12:00-12:50 13:00-13:50,BZ-02-104 BZ-02-104,,60 60,Y 05/07/2024 - AM,0121 - JBS
10,01A,THU,12:00-12:50 13:00-13:50,BZ-02-090 BZ-02-090,L L B B B B,30 30,Y 05/07/2024 - AM,0121 - JBS
11,01B,THU,08:00-08:50 09:00-09:50,BZ-02-090 BZ-02-090,,30 30,Y 05/07/2024 - AM,0121 - JBS

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,WED,10:00-10:50 11:00-11:50,BZ-02-106 BZ-02-106,,60 60,N,01443 - MIBUO
3,01A,TUE,16:00-16:50 17:00-17:50,BZ-03-076 BZ-03-076,L L B B B B,30 30,N,01443 - MIBUO
4,01B,TUE,14:00-14:50 15:00-15:50,BZ-03-076 BZ-03-076,,30 30,N,01443 - MIBUO
5,Semester II Academic Session 2023/2024,,,,,,,
6,Sec Day Time Loc Mode Cap Staff Exam,,,,,,,
7,L L B B N 01 WED 10:00-10:50 BZ-02-100 30 0144...,,,,,,,
8,N 01A TUE 16:00-16:50 BZ-04-068 30 01443 - MIB...,,,,,,,

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,THU,16:00-16:50 17:00-17:50,BZ-02-106 BZ-02-106,,60 60,N,01891 - AFBMR
3,01A,THU,10:00-10:50 11:00-11:50,BZ-01-092 BZ-01-092,L L B B B B,30 30,N,01891 - AFBMR
4,01B,MON,12:00-12:50 13:00-13:50,BZ-01-092 BZ-01-092,,30 30,N,01891 - AFBMR

                                                   0
0             Semester II Academic Session 2023/2024
1               Sec Day Time Loc Mode Cap Exam Staff
2  L L B B 01 Y THU 01/07/2024 - PM 08:00-08:50 B...
3  01A Y THU 01/07/2024 - PM 14:00-14:50 BZ-03-06...

                                                   0
0              Semester I Academic Session 2023/2024
1               Sec Day Time Loc Mode Cap Exam Staff
2  L L B B 2 2 2 2 01 Y WED 30/01/2024 - AM 10:00...
3  01A Y TUE 30/01/2024 - AM 16:00-16:50 BZ-03-06...
4             Semester II Academic Session 2023/2024
5               Sec Day Time Loc Mode Cap Staff Exam
6  L L B B 01 Y FRI 28/06/2024 - AM 08:00-08:50 B...
7  01A Y MON 28/06/2024 - AM 08:00-08:50 BZ-03-06...

                                                   0
0              Semester I Academic Session 2023/2024
1               Exam Sec Day Time Loc Mode Cap Staff
2  L L B B 01 Y MON 07/02/2024 - AM 14:00-14:50 B...
3  01A Y TUE 07/02/2024 - AM 10:00-10:50 BZ-03-06...

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
2,01,MON,08:00-08:50 09:00-09:50,BZ-02-105 BZ-02-105,,60 60,Y 01/02/2024 - AM,01982 - ZBI
3,01A,FRI,08:00-08:50 09:00-09:50,BZ-03-069 BZ-03-069,L L B B B B,30 30,Y 01/02/2024 - AM,01982 - ZBI
4,01C,MON,14:00-14:50 15:00-15:50,BZ-03-069 BZ-03-069,,30 30,Y 01/02/2024 - AM,01982 - ZBI

                                                   0
0             Semester II Academic Session 2023/2024
1               Exam Sec Day Time Loc Mode Cap Staff
2  L L B B 01 Y FRI 08/07/2024 - PM 10:00-10:50 B...
3  01A Y TUE 08/07/2024 - PM 16:00-16:50 BZ-03-06...

,0,1,2,3,4,5,6,7
0,Semester I Academic Session 2023/2024,,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,,Exam,Staff
2,01,THU,14:00-14:50 15:00-15:50,BZ-02-105 BZ-02-105,,90 90,Y 02/02/2024 - AM,01898 - SBIH
3,01A,WED,08:00-08:50 09:00-09:50,BZ-03-064 BZ-03-064,,30 30,Y 02/02/2024 - AM,01898 - SBIH
4,01C,THU,08:00-08:50 09:00-09:50,BZ-03-064 BZ-03-064,L L B B B B B B L L B B,30 30,Y 02/02/2024 - AM,01898 - SBIH
5,01D,THU,10:00-10:50 11:00-11:50,BZ-03-064 BZ-03-064,,30 30,Y 02/02/2024 - AM,01868 - AFBZA
6,02,THU,14:00-14:50 15:00-15:50,BZ-02-105 BZ-02-105,,30 30,Y 02/02/2024 - AM,01898 - SBIH
7,02A,WED,08:00-08:50 09:00-09:50,BZ-03-064 BZ-03-064,,30 30,Y 02/02/2024 - AM,01898 - SBIH

,0,1,2,3,4,5,6,7
0,Semester II Academic Session 2023/2024,,,,,,,
1,Sec,Day,Time,Loc,Mode,Cap,Exam,Staff
2,01,TUE,12:00-12:50 13:00-13:50,BZ-02-105 BZ-02-105,,60 60,Y 04/07/2024 - PM,01982 - ZBI
3,01B,THU,08:00-08:50 09:00-09:50,BZ-03-064 BZ-03-064,,30 30,Y 04/07/2024 - PM,01982 - ZBI
4,01C,WED,08:00-08:50 09:00-09:50,BZ-03-064 BZ-03-064,L L B B B B L L B B,30 30,Y 04/07/2024 - PM,01982 - ZBI
5,02,TUE,12:00-12:50 13:00-13:50,BZ-02-105 BZ-02-105,,30 30,Y 04/07/2024 - PM,01982 - ZBI
6,02A,THU,12:00-12:50 13:00-13:50,BZ-03-064 BZ-03-064,,30 30,Y 04/07/2024 - PM,01982 - ZBI

,0,1,2,3,4,5,6
0,Semester I Academic Session 2023/2024,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,Exam,Staff
2,01,,,,500,,TBA
3,01- CNRG,,,,12,,TBA
4,,,,,,,
5,02- CSRG,,,,7 1,,TBA
6,,,,,,,
7,03-Cy- SIG,,,,5,N N N N N N N,TBA
8,,,,,,,
9,04- DBIS,,,,,,TBA
10,,,,,,,
11,05- DSSim,,,,8 8 1,,TBA
12,,,,,,,
13,06- EDUT ECH,,,,0,,TBA
14,,,,,,,
15,07-ISP,,,,11,,TBA
16,08- KECL,,,,7 2,N N N N,TBA
17,,,,,,,
18,09- SERG,,,,1,,TBA
19,,,,,,,
20,10- SCOR E,,,,13,,TBA
21,,,,,,,
22,11- MIRG,,,,21,,TBA
23,,,,,,,
24,12- VISIC,,,,9 1,N N N,TBA
25,,,,,,,
26,13-IoT,,,,3,,TBA
27,Semester II Academic Session 2023/2024,,,,,,
28,Sec Day,Time,Loc,Mode,Cap,Exam,Staff
29,01,,,,400,,TBA
30,01- CNRG,,,,23,,TBA
31,,,,,,,
32,02- CSRG,,,,8 3,,TBA
33,,,,,,,
34,03-Cy- SIG,,,,7,N N N N N N N,TBA
35,,,,,,,
36,04- DBIS,,,,18,,TBA
37,,,,,,,
38,05- DSSim,,,,17,,TBA
39,,,,,,,
40,06- EDUT ECH,,,,28,,TBA
41,,,,,,,
42,07-ISP,,,,20,,TBA
43,08- KECL,,,,33,N N N N,TBA
44,,,,,,,
45,09- SERG,,,,20,,TBA
46,,,,,,,
47,10- SCOR E,,,,13,,TBA
48,,,,,,,
49,11- MIRG,,,,17,,TBA
50,,,,,,,
51,12- VISIC,,,,20,N N N,TBA
52,,,,,,,
53,13-IoT,,,,30,,TBA

,0,1,2,3,4,5,6
0,Semester I Academic Session 2023/2024,,,,,,
1,Sec Day Time Loc Mode Cap,,,,,Exam,Staff
2,01,,,,29,,TBA
3,01- CNRG,,,,23,,TBA
4,,,,,,,
5,02- CSRG,,,,10,,TBA
6,,,,,,,
7,03-Cy- SIR,,,,37,N N N N N N N,TBA
8,,,,,,,
9,04- DBIS,,,,22,,TBA
10,,,,,,,
11,05- DSSim,,,,18,,TBA
12,,,,,,,
13,06- EDUT ECH,,,,32,,TBA
14,,,,,,,
15,07-ISP,,,,22,,TBA
16,08- KECL,,,,23,N N N N,TBA
17,,,,,,,
18,09- SERG,,,,22,,TBA
19,,,,,,,
20,10- SCOR E,,,,15,,TBA
21,,,,,,,
22,11- MIRG,,,,20,,TBA
23,,,,,,,
24,12- VISIC,,,,27,N N N,TBA
25,,,,,,,
26,IoT,,,,11,,TBA
27,Semester II Academic Session 2023/2024,,,,,,
28,Sec Day,Time,Loc,Mode,Cap,Exam,Staff
29,01,,,,500,,TBA
30,01- CNRG,,,,12,,TBA
31,,,,,,,
32,02- CSRG,,,,7 1,,TBA
33,,,,,,,
34,03-Cy- SIG,,,,5,N N N N N N N,TBA
35,,,,,,,
36,04- DBIS,,,,,,TBA
37,,,,,,,
38,05- DSSim,,,,8 8 1,,TBA
39,,,,,,,
40,06- EDUT ECH,,,,0,,TBA
41,,,,,,,
42,07-ISP,,,,11,,TBA
43,08- KECL,,,,7 2,N N N N,TBA
44,,,,,,,
45,09- SERG,,,,1,,TBA
46,,,,,,,
47,10- SCOR E,,,,13,,TBA
48,,,,,,,
49,11- MIRG,,,,21,,TBA
50,,,,,,,
51,12- VISIC,,,,9 3,N N N,TBA
52,,,,,,,
53,13-IoT,,,,0,,TBA

                                        0
0   Semester I Academic Session 2023/2024
1    Sec Day Time Loc Mode Cap Exam Staff
2                            01 300 N TBA
3  Semester II Academic Session 2023/2024
4    Sec Day Time Loc Mode Cap Exam Staff
5                            01 500 N TBA

In [ ]:
tables[0].df.iloc[1, :6] = tables[0].df.iloc[1, 0].split()[:6]
tables[0].df

In [ ]:
modes = tables[0].df.iloc[3, 4].split()[:8]

for i in range(2, 6):
    tables[0].df.iloc[i, 4] = modes[2 * (i - 2)] + modes[2 * (i - 2) + 1]

tables[0].df

In [21]:
import pdfplumber
with pdfplumber.open("COURSE_CATALOG_IJA.pdf") as pdf:

    extracted_text = ''

    for page in pdf.pages:
        text = page.extract_text()
        extracted_text += text

extracted_text.replace("\n", " ").replace("03-OCT-23 11:09 AM", "")

"COURSE TIMETABLE Faculty : FACULTY OF COMPUTING (FK) Campus : GAMBANG Level : DEGREE Semester I Academic Session 2023/2024 Course Code : BCI2023 Sec Day Time Loc Mode Cap Exam Staff Course Name : DATABASE SYSTEMS 01G FRI 10:00-10:50 FSK15 B 36 Y30/01/2024 - AM 01469 - LSC Pre-Requisite : NO 11:00-11:50 FSK15 B 36 Remarks : NO THU 08:00-08:50 Z01-0004 L 36 09:00-09:50 Z01-0004 L 36 02G FRI 08:00-08:50 FSK15 B 36 Y30/01/2024 - AM 01469 - LSC 09:00-09:50 FSK15 B 36 THU 08:00-08:50 Z01-0004 L 36 09:00-09:50 Z01-0004 L 36 Couse Synopsis : The course emphasizes on the importance of data to an organization and how the data should be managed. Database management system (DBMS) will be viewed as a solution to the problems of file processing system. Aspects of relational database design will be covered in details. This includes database development life cycle, database architecture, data models, and normalization process. Structured Query Language (SQL) will be discussed and empahsised as query language in database management. Students will be given a real life problem to design and develop a database application system. In the later part of the course students will be exposed to the latest developments in database architecture.(cid:13) Campus : GAMBANG Level : DEGREE Semester I Academic Session 2023/2024 Course Code : BCI1093 Sec Day Time Loc Mode Cap Exam Staff Course Name : DATA STRUCTURE & ALGORITHMS 01G FRI 08:00-08:50 FSK14 B 36 Y25/01/2024 - AM TBA0001 - ES( Pre-Requisite : BCI1023, BCS1023, 09:00-09:50 FSK14 B 36 Remarks : NO TUE 08:00-08:50 Z01-0004 L 36 09:00-09:50 Z01-0004 L 36 02G FRI 10:00-10:50 FSK14 B 35 Y25/01/2024 - AM TBA0001 - ES( 11:00-11:50 FSK14 B 35 TUE 08:00-08:50 Z01-0004 L 35 09:00-09:50 Z01-0004 L 35 Couse Synopsis : This course is designed to expose the students to the data structures and algorithm. It provide theoretical basis in data structures and the application of data structures is based on standard algorithms. Students must also be able to transform the data structure and algorithms problems into the computer programs. COURSE TIMETABLE Faculty : FACULTY OF COMPUTING (FK) Campus : GAMBANG Level : DEGREE Semester I Academic Session 2023/2024 Course Code : BCI1103 Sec Day Time Loc Mode Cap Exam Staff Course Name : COMPUTER PROGRAMMING 01A WED 12:00-12:50 FKPPT- L- 01B B 30 N 01100 - ZRBMA Pre-Requisite : NO 13:00-13:50 FKPPT- L- 01B B 30 Remarks : 01G - BSK BSP BPS 02G - BSK BSP BPS 01B WED 12:00-12:50 FKPPT- L- 01B B 30 N 01100 - ZRBMA 04G - BMM BMA 13:00-13:50 FKPPT- L- 01B B 30 05G - BKC 01G MON 12:00-12:50 W-DK-13 L 60 N 01100 - ZRBMA 07G - BEE 10P - BTE 13:00-13:50 W-DK-13 L 60 11P - BHM 02A THU 12:00-12:50 FKPPT- L- 01B B 30 N 01100 - ZRBMA 13P - BTD BTA BTG 13:00-13:50 FKPPT- L- 01B B 30 15P - BTS 02B THU 12:00-12:50 FKPPT- L- 01B B 30 N 01100 - ZRBMA 13:00-13:50 FKPPT- L- 01B B 30 02G TUE 12:00-12:50 W-DK-13 L 60 N 01100 - ZRBMA 13:00-13:50 W-DK-13 L 60 03A WED 14:00-14:50 ET-L-01 B 20 N 01985 - M'BM 15:00-15:50 ET-L-01 B 20 03B WED 14:00-14:50 ET-L-01 B 20 N 01985 - M'BM 15:00-15:50 ET-L-01 B 20 03G FRI 10:00-10:50 Y-DK-03 L 40 N 01985 - M'BM 11:00-11:50 Y-DK-03 L 40 04A FRI 10:00-10:50 ET-L-02 B 30 N FP0040 - IBMA 11:00-11:50 ET-L-02 B 30 04B THU 08:00-08:50 ET-L-02 B 30 N FP0040 - IBMA 09:00-09:50 ET-L-02 B 30 04G WED 08:00-08:50 Y01-0018 L 60 N FP0040 - IBMA 09:00-09:50 Y01-0018 L 60 06A WED 10:00-10:50 FSK12 B 30 N FP0040 - IBMA 11:00-11:50 FSK12 B 30 06B WED 10:00-10:50 FSK12 B 30 N FP0040 - IBMA 11:00-11:50 FSK12 B 30 06G MON 10:00-10:50 Y01-1010 L 60 N FP0040 - IBMA 11:00-11:50 Y01-1010 L 60 07A TUE 14:00-14:50 ETIM-L-01 B 30 N 01985 - M'BM 15:00-15:50 ETIM-L-01 B 30 07G WED 08:00-08:50 ETIM-L-01 L 30 N 01985 - M'BM 09:00-09:50 ETIM-L-01 L 30 Semester II Academic Session 2023/2024 Sec Day Time Loc Mode Cap Exam Staff 01A WED 12:00-12:50 FKPPT- L- 01B B 30 N FP0040 - IBMA 13:00-13:50 FKPPT- L- 01B B 30 01B WED 12:00-12:50 FKPPT- L- 01B B 30 N FP0040 - IBMA 13:00-13:50 FKPPT- L- 01B B 30 01G MON 12:00-12:50 W-DK-13 L 60 N FP0040 - IBMA 13:00-13:50 W-DK-13 L 60 02A THU 12:00-12:50 FKPPT- L- 01B B 30 N FP0040 - IBMA 13:00-13:50 FKPPT- L- 01B B 30 02B THU 12:00-12:50 FKPPT- L- 01B B 30 N FP0040 - IBMA 13:00-13:50 FKPPT- L- 01B B 30 02G TUE 12:00-12:50 W-DK-13 L 60 N FP0040 - IBMA 13:00-13:50 W-DK-13 L 60 04A THU 14:00-14:50 ET-L-01 B 30 N 01100 - ZRBMA 15:00-15:50 ET-L-01 B 30 04G TUE 14:00-14:50 ET-L-01 L 30 N 01100 - ZRBMA 15:00-15:50 ET-L-01 L 30 05A THU 16:00-16:50 FTA16L B 30 N 01469 - LSC 17:00-17:50 FTA16L B 30 05B THU 16:00-16:50 FTA16L B 30 N 01469 - LSC 17:00-17:50 FTA16L B 30 05G TUE 16:00-16:50 W-DKU-K-01 L 60 N 01469 - LSC 17:00-17:50 W-DKU-K-01 L 60 06A THU 08:00-08:50 ET-L-02 B 30 N 01469 - LSC 09:00-09:50 ET-L-02 B 30 06B THU 08:00-08:50 ET-L-02 B 30 N 01469 - LSC 09:00-09:50 ET-L-02 B 30 06G MON 10:00-10:50 Y01-1010 L 60 N 01469 - LSC 11:00-11:50 Y01-1010 L 60 07A WED 14:00-14:50 FKASA11B B 30 N 0544 - JBS 15:00-15:50 FKASA11B B 30 07G MON 14:00-14:50 FKASA11A L 30 N 0544 - JBS 15:00-15:50 FKASA11A L 30 08A THU 12:00-12:50 FKASA11A B 30 N 0544 - JBS 13:00-13:50 FKASA11A B 30 COURSE TIMETABLE Faculty : FACULTY OF COMPUTING (FK) 08G TUE 12:00-12:50 FKASA11A L 30 N 0544 - JBS 13:00-13:50 FKASA11A L 30 Couse Synopsis : This subject aims to introduce the fundamental element and feasibilities of the computer programming to solve identified problems. The contents emphasis not only on the theoretical knowledge of programming but also the practical implementation in solving applications problem. Students will learn basic structure of computer programming including variables and data types, input and output instruction, statements, functions, arrays, string, pointers and files operations. Students will be taught on developing a program to solve general engineering problems, mathematical equations as well as displaying the data via 2D and/or 3D graphs. Campus : GAMBANG Level : DEGREE Semester I Academic Session 2023/2024 Course Code : BCU1013 Sec Day Time Loc Mode Cap Exam Staff Course Name : PROBLEM SOLVING & PROGRAMMING CONCEPT 01G MON 10:00-10:50 Z01-0003 L 35 Y25/01/2024 - AM 01918 - YBMN Pre-Requisite : NO 11:00-11:50 Z01-0003 L 35 Remarks : NO TUE 08:00-08:50 FSK14 B 35 09:00-09:50 FSK14 B 35 02G MON 10:00-10:50 Z01-0003 L 30 Y25/01/2024 - AM 01918 - YBMN 11:00-11:50 Z01-0003 L 30 TUE 12:00-12:50 FSK14 B 30 13:00-13:50 FSK14 B 30 Couse Synopsis : Campus : GAMBANG Level : DEGREE Semester II Academic Session 2023/2024 Course Code : BCU1023 Sec Day Time Loc Mode Cap Exam Staff Course Name : PROGRAMMING TECHNIQUES 01G THU 10:00-10:50 FSK14 B 35 Y27/06/2024 - AM 01918 - YBMN Pre-Requisite : BCU1013, 11:00-11:50 FSK14 B 35 Remarks : NO WED 10:00-10:50 Z01-0003 L 35 11:00-11:50 Z01-0003 L 35 02G THU 14:00-14:50 FSK14 B 35 Y27/06/2024 - AM 01918 - YBMN 15:00-15:50 FSK14 B 35 WED 10:00-10:50 Z01-0003 L 35 11:00-11:50 Z01-0003 L 35 Couse Synopsis : COURSE TIMETABLE Faculty : FACULTY OF COMPUTING (FK) Campus : PEKAN Level : DEGREE Semester I Academic Session 2023/2024 Course Code : BCI1023 Sec Day Time Loc Mode Cap Exam Staff Course Name : PROGRAMMING TECHNIQUES 01 WED 10:00-10:50 BZ-02-100 L 30 Y 01657 - ZBM Pre-Requisite : BCI1143, 11:00-11:50 BZ-02-100 L 30 Remarks : NO 01A MON 10:00-10:50 BZ-03-083 B 30 Y 01657 - ZBM 11:00-11:50 BZ-03-083 B 30 Semester II Academic Session 2023/2024 Sec Day Time Loc Mode Cap Exam Staff 01 MON 10:00-10:50 BZ-02-096 L 60 Y27/06/2024 - AM 01746 - MABI 11:00-11:50 BZ-02-096 L 60 01A FRI 10:00-10:50 BZ-03-083 B 30 Y27/06/2024 - AM 01746 - MABI 11:00-11:50 BZ-03-083 B 30 01B FRI 08:00-08:50 BZ-03-083 B 30 Y27/06/2024 - AM 01746 - MABI 09:00-09:50 BZ-03-083 B 30 02 TUE 10:00-10:50 BZ-02-096 L 60 Y27/06/2024 - AM 01746 - MABI 11:00-11:50 BZ-02-096 L 60 02A MON 16:00-16:50 BZ-03-083 B 30 Y27/06/2024 - AM 01746 - MABI 17:00-17:50 BZ-03-083 B 30 02B MON 14:00-14:50 BZ-03-083 B 30 Y27/06/2024 - AM 01746 - MABI 15:00-15:50 BZ-03-083 B 30 03 FRI 10:00-10:50 BZ-01-121 L 60 Y27/06/2024 - AM 01469 - LSC 11:00-11:50 BZ-01-121 L 60 03A MON 10:00-10:50 BZ-03-083 B 30 Y27/06/2024 - AM 01469 - LSC 11:00-11:50 BZ-03-083 B 30 03B TUE 12:00-12:50 BZ-03-083 B 30 Y27/06/2024 - AM 01469 - LSC 13:00-13:50 BZ-03-083 B 30 04 MON 16:00-16:50 BZ-02-100 L 60 Y27/06/2024 - AM 01469 - LSC 17:00-17:50 BZ-02-100 L 60 04A TUE 10:00-10:50 BZ-03-083 B 30 Y27/06/2024 - AM 01469 - LSC 11:00-11:50 BZ-03-083 B 30 04B THU 12:00-12:50 BZ-03-083 B 30 Y27/06/2024 - AM 01469 - LSC 13:00-13:50 BZ-03-083 B 30 Couse Synopsis : This course discusses on understanding problems and translating them into computer solution techniques using programming language. This course enables students to apply programming techniques, write programming codes from given problems and execute programming codes successfully. "

In [45]:
import re

pattern = r"Course Code : (\w+)\s+((?:(?!Course Code :).)*)Course Name : (.+?)\n"
matches = re.findall(pattern, extracted_text, re.DOTALL)

for match in matches:
    course_code, extra_text, course_name = match
    print(f"Course Code: {course_code}\nCourse Name: {course_name}\n")

Course Code: BCI2023
Course Name: DATABASE SYSTEMS

Course Code: BCI1093
Course Name: DATA STRUCTURE & ALGORITHMS

Course Code: BCI1103
Course Name: COMPUTER PROGRAMMING

Course Code: BCU1013
Course Name: PROBLEM SOLVING & PROGRAMMING

Course Code: BCU1023
Course Name: PROGRAMMING TECHNIQUES

Course Code: BCI1023
Course Name: PROGRAMMING TECHNIQUES